/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.193
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// ActivityGenericStatus
    /// </summary>
    [DataContract(Name = "ActivityGenericStatus")]
    public partial class ActivityGenericStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityGenericStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public ActivityGenericStatus()
        {
        }

        /// <summary>
        /// The total number of tags that this activity will delete.
        /// </summary>
        /// <value>The total number of tags that this activity will delete.</value>
        /// <example>89</example>
        [DataMember(Name = "items_total_count", EmitDefaultValue = false)]
        public int ItemsTotalCount { get; private set; }

        /// <summary>
        /// Returns false as ItemsTotalCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeItemsTotalCount()
        {
            return false;
        }
        /// <summary>
        /// The number of tags that this activity has currently deleted.
        /// </summary>
        /// <value>The number of tags that this activity has currently deleted.</value>
        /// <example>89</example>
        [DataMember(Name = "items_completed_count", EmitDefaultValue = false)]
        public int ItemsCompletedCount { get; private set; }

        /// <summary>
        /// Returns false as ItemsCompletedCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeItemsCompletedCount()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivityGenericStatus {\n");
            sb.Append("  ItemsTotalCount: ").Append(ItemsTotalCount).Append("\n");
            sb.Append("  ItemsCompletedCount: ").Append(ItemsCompletedCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
