/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// The workflow definition containing tasks, status, and metadata. Internal fields such as correlationMetadata and parameters are excluded to prevent leaking accountId.
    /// </summary>
    [DataContract(Name = "AutomationFlow_workflow_def")]
    public partial class AutomationFlowWorkflowDef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutomationFlowWorkflowDef" /> class.
        /// </summary>
        /// <param name="tasks">tasks.</param>
        /// <param name="status">status.</param>
        /// <param name="varNamespace">varNamespace.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="timeout">timeout.</param>
        /// <param name="upgradable">upgradable.</param>
        public AutomationFlowWorkflowDef(List<Object> tasks = default(List<Object>), string status = default(string), string varNamespace = default(string), Object metadata = default(Object), Object timeout = default(Object), bool upgradable = default(bool))
        {
            this.Tasks = tasks;
            this.Status = status;
            this.VarNamespace = varNamespace;
            this.Metadata = metadata;
            this.Timeout = timeout;
            this.Upgradable = upgradable;
        }

        /// <summary>
        /// Gets or Sets Tasks
        /// </summary>
        [DataMember(Name = "tasks", EmitDefaultValue = false)]
        public List<Object> Tasks { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets VarNamespace
        /// </summary>
        [DataMember(Name = "namespace", EmitDefaultValue = false)]
        public string VarNamespace { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Timeout
        /// </summary>
        [DataMember(Name = "timeout", EmitDefaultValue = false)]
        public Object Timeout { get; set; }

        /// <summary>
        /// Gets or Sets Upgradable
        /// </summary>
        [DataMember(Name = "upgradable", EmitDefaultValue = true)]
        public bool Upgradable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutomationFlowWorkflowDef {\n");
            sb.Append("  Tasks: ").Append(Tasks).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  VarNamespace: ").Append(VarNamespace).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Timeout: ").Append(Timeout).Append("\n");
            sb.Append("  Upgradable: ").Append(Upgradable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
