/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// AutomationCampaign
    /// </summary>
    [DataContract(Name = "AutomationCampaign")]
    public partial class AutomationCampaign : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutomationCampaign" /> class.
        /// </summary>
        /// <param name="id">The unique identifier for the automation campaign workflow..</param>
        /// <param name="name">The name of the automation campaign..</param>
        /// <param name="description">The description of the automation campaign..</param>
        /// <param name="structuredTags">structuredTags.</param>
        /// <param name="activeDefinition">activeDefinition.</param>
        /// <param name="draftDefinition">draftDefinition.</param>
        /// <param name="isNameExplicitlySet">Indicates whether the automation campaign name was explicitly set..</param>
        public AutomationCampaign(string id = default(string), string name = default(string), string description = default(string), List<AutomationCampaignStructuredTagsInner> structuredTags = default(List<AutomationCampaignStructuredTagsInner>), AutomationCampaignActiveDefinition activeDefinition = default(AutomationCampaignActiveDefinition), AutomationCampaignActiveDefinition draftDefinition = default(AutomationCampaignActiveDefinition), bool isNameExplicitlySet = default(bool))
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.StructuredTags = structuredTags;
            this.ActiveDefinition = activeDefinition;
            this.DraftDefinition = draftDefinition;
            this.IsNameExplicitlySet = isNameExplicitlySet;
        }

        /// <summary>
        /// The unique identifier for the automation campaign workflow.
        /// </summary>
        /// <value>The unique identifier for the automation campaign workflow.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The name of the automation campaign.
        /// </summary>
        /// <value>The name of the automation campaign.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The description of the automation campaign.
        /// </summary>
        /// <value>The description of the automation campaign.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets StructuredTags
        /// </summary>
        [DataMember(Name = "structured_tags", EmitDefaultValue = false)]
        public List<AutomationCampaignStructuredTagsInner> StructuredTags { get; set; }

        /// <summary>
        /// Gets or Sets ActiveDefinition
        /// </summary>
        [DataMember(Name = "active_definition", EmitDefaultValue = false)]
        public AutomationCampaignActiveDefinition ActiveDefinition { get; set; }

        /// <summary>
        /// Gets or Sets DraftDefinition
        /// </summary>
        [DataMember(Name = "draft_definition", EmitDefaultValue = false)]
        public AutomationCampaignActiveDefinition DraftDefinition { get; set; }

        /// <summary>
        /// Indicates whether the automation campaign name was explicitly set.
        /// </summary>
        /// <value>Indicates whether the automation campaign name was explicitly set.</value>
        [DataMember(Name = "is_name_explicitly_set", EmitDefaultValue = true)]
        public bool IsNameExplicitlySet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutomationCampaign {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  StructuredTags: ").Append(StructuredTags).Append("\n");
            sb.Append("  ActiveDefinition: ").Append(ActiveDefinition).Append("\n");
            sb.Append("  DraftDefinition: ").Append(DraftDefinition).Append("\n");
            sb.Append("  IsNameExplicitlySet: ").Append(IsNameExplicitlySet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
