/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.185
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// ContactSmsChannel
    /// </summary>
    [DataContract(Name = "ContactSmsChannel")]
    public partial class ContactSmsChannel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactSmsChannel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContactSmsChannel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactSmsChannel" /> class.
        /// </summary>
        /// <param name="fullSmsAddress">The SMS-capable phone number for the Contact, including the dial code (required).</param>
        /// <param name="smsChannelConsents">The consents for the SMS Channel. (required).</param>
        public ContactSmsChannel(string fullSmsAddress = default(string), List<UpdateContactRequestSmsChannelSmsChannelConsentsInner> smsChannelConsents = default(List<UpdateContactRequestSmsChannelSmsChannelConsentsInner>))
        {
            // to ensure "fullSmsAddress" is required (not null)
            if (fullSmsAddress == null)
            {
                throw new ArgumentNullException("fullSmsAddress is a required property for ContactSmsChannel and cannot be null");
            }
            this.FullSmsAddress = fullSmsAddress;
            // to ensure "smsChannelConsents" is required (not null)
            if (smsChannelConsents == null)
            {
                throw new ArgumentNullException("smsChannelConsents is a required property for ContactSmsChannel and cannot be null");
            }
            this.SmsChannelConsents = smsChannelConsents;
        }

        /// <summary>
        /// The SMS-capable phone number for the Contact, including the dial code
        /// </summary>
        /// <value>The SMS-capable phone number for the Contact, including the dial code</value>
        /// <example>17815551212</example>
        [DataMember(Name = "full_sms_address", IsRequired = true, EmitDefaultValue = true)]
        public string FullSmsAddress { get; set; }

        /// <summary>
        /// The consents for the SMS Channel.
        /// </summary>
        /// <value>The consents for the SMS Channel.</value>
        [DataMember(Name = "sms_channel_consents", IsRequired = true, EmitDefaultValue = true)]
        public List<UpdateContactRequestSmsChannelSmsChannelConsentsInner> SmsChannelConsents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContactSmsChannel {\n");
            sb.Append("  FullSmsAddress: ").Append(FullSmsAddress).Append("\n");
            sb.Append("  SmsChannelConsents: ").Append(SmsChannelConsents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
