/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.53
 *
 * The version of the OpenAPI document: 1.0.171
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// ContactResubscribeRequest
    /// </summary>
    [DataContract(Name = "ContactResubscribeRequest")]
    public partial class ContactResubscribeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactResubscribeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContactResubscribeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactResubscribeRequest" /> class.
        /// </summary>
        /// <param name="listIds">Array of list id values. Constant Contact adds the resubscribed contact to the contact lists you provide in the array. (required).</param>
        public ContactResubscribeRequest(List<Guid> listIds = default(List<Guid>))
        {
            // to ensure "listIds" is required (not null)
            if (listIds == null)
            {
                throw new ArgumentNullException("listIds is a required property for ContactResubscribeRequest and cannot be null");
            }
            this.ListIds = listIds;
        }

        /// <summary>
        /// Array of list id values. Constant Contact adds the resubscribed contact to the contact lists you provide in the array.
        /// </summary>
        /// <value>Array of list id values. Constant Contact adds the resubscribed contact to the contact lists you provide in the array.</value>
        [DataMember(Name = "list_ids", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> ListIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContactResubscribeRequest {\n");
            sb.Append("  ListIds: ").Append(ListIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
