/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.185
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// ContactCampaignActivitiesSummary
    /// </summary>
    [DataContract(Name = "ContactCampaignActivitiesSummary")]
    public partial class ContactCampaignActivitiesSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactCampaignActivitiesSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContactCampaignActivitiesSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactCampaignActivitiesSummary" /> class.
        /// </summary>
        /// <param name="contactId">Unique id of the contact that will have their activity summarized. (required).</param>
        /// <param name="campaignActivities">A summary of all the actions for a contact. (required).</param>
        /// <param name="links">links.</param>
        public ContactCampaignActivitiesSummary(Guid contactId = default(Guid), List<GetContactTrackingCountReport200ResponseCampaignActivitiesInner> campaignActivities = default(List<GetContactTrackingCountReport200ResponseCampaignActivitiesInner>), GetContactTrackingCountReport200ResponseLinks links = default(GetContactTrackingCountReport200ResponseLinks))
        {
            this.ContactId = contactId;
            // to ensure "campaignActivities" is required (not null)
            if (campaignActivities == null)
            {
                throw new ArgumentNullException("campaignActivities is a required property for ContactCampaignActivitiesSummary and cannot be null");
            }
            this.CampaignActivities = campaignActivities;
            this.Links = links;
        }

        /// <summary>
        /// Unique id of the contact that will have their activity summarized.
        /// </summary>
        /// <value>Unique id of the contact that will have their activity summarized.</value>
        /// <example>71600990-908b-11e6-907f-0000166bff25</example>
        [DataMember(Name = "contact_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid ContactId { get; set; }

        /// <summary>
        /// A summary of all the actions for a contact.
        /// </summary>
        /// <value>A summary of all the actions for a contact.</value>
        [DataMember(Name = "campaign_activities", IsRequired = true, EmitDefaultValue = true)]
        public List<GetContactTrackingCountReport200ResponseCampaignActivitiesInner> CampaignActivities { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = false)]
        public GetContactTrackingCountReport200ResponseLinks Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContactCampaignActivitiesSummary {\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  CampaignActivities: ").Append(CampaignActivities).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
