/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// Describes a post to a single social profile, including the target profile and its current status on that network.
    /// </summary>
    [DataContract(Name = "createSocialPost_request_profile_posts_inner_profiles_inner")]
    public partial class CreateSocialPostRequestProfilePostsInnerProfilesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSocialPostRequestProfilePostsInnerProfilesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateSocialPostRequestProfilePostsInnerProfilesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSocialPostRequestProfilePostsInnerProfilesInner" /> class.
        /// </summary>
        /// <param name="profileId">The unique identifier for the profile to post to. Use the &lt;code&gt;profile_id&lt;/code&gt; from &lt;code&gt;GET /social/profiles&lt;/code&gt;. (required).</param>
        public CreateSocialPostRequestProfilePostsInnerProfilesInner(string profileId = default(string))
        {
            // to ensure "profileId" is required (not null)
            if (profileId == null)
            {
                throw new ArgumentNullException("profileId is a required property for CreateSocialPostRequestProfilePostsInnerProfilesInner and cannot be null");
            }
            this.ProfileId = profileId;
        }

        /// <summary>
        /// The human-readable username of the account that owns this profile.
        /// </summary>
        /// <value>The human-readable username of the account that owns this profile.</value>
        [DataMember(Name = "account_username", EmitDefaultValue = false)]
        public string AccountUsername { get; private set; }

        /// <summary>
        /// Returns false as AccountUsername should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAccountUsername()
        {
            return false;
        }
        /// <summary>
        /// The campaign activity ID for this post on the specified profile. Generated by the server on creation. When updating a post, existing profile entries should include their original &lt;code&gt;campaign_activity_id&lt;/code&gt;.
        /// </summary>
        /// <value>The campaign activity ID for this post on the specified profile. Generated by the server on creation. When updating a post, existing profile entries should include their original &lt;code&gt;campaign_activity_id&lt;/code&gt;.</value>
        [DataMember(Name = "campaign_activity_id", EmitDefaultValue = false)]
        public string CampaignActivityId { get; private set; }

        /// <summary>
        /// Returns false as CampaignActivityId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCampaignActivityId()
        {
            return false;
        }
        /// <summary>
        /// The status of the post activity for this profile.
        /// </summary>
        /// <value>The status of the post activity for this profile.</value>
        [DataMember(Name = "campaign_activity_status", EmitDefaultValue = false)]
        public string CampaignActivityStatus { get; private set; }

        /// <summary>
        /// Returns false as CampaignActivityStatus should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCampaignActivityStatus()
        {
            return false;
        }
        /// <summary>
        /// The activity&#39;s timestamp. For &lt;code&gt;SCHEDULED&lt;/code&gt; activities, this is typically the same as the scheduled publish time; otherwise, it is the last-modified timestamp.
        /// </summary>
        /// <value>The activity&#39;s timestamp. For &lt;code&gt;SCHEDULED&lt;/code&gt; activities, this is typically the same as the scheduled publish time; otherwise, it is the last-modified timestamp.</value>
        [DataMember(Name = "campaign_activity_status_date", EmitDefaultValue = false)]
        public DateTime CampaignActivityStatusDate { get; private set; }

        /// <summary>
        /// Returns false as CampaignActivityStatusDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCampaignActivityStatusDate()
        {
            return false;
        }
        /// <summary>
        /// A human-readable message describing the current status of the post activity. Can be a generic Constant Contact message or a specific message reported by the social network.
        /// </summary>
        /// <value>A human-readable message describing the current status of the post activity. Can be a generic Constant Contact message or a specific message reported by the social network.</value>
        [DataMember(Name = "campaign_activity_status_message", EmitDefaultValue = false)]
        public string CampaignActivityStatusMessage { get; private set; }

        /// <summary>
        /// Returns false as CampaignActivityStatusMessage should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCampaignActivityStatusMessage()
        {
            return false;
        }
        /// <summary>
        /// The URL of the profile&#39;s image. This image may become stale and is only refreshed when retrieving profiles with &lt;code&gt;include&#x3D;accessible&lt;/code&gt;.
        /// </summary>
        /// <value>The URL of the profile&#39;s image. This image may become stale and is only refreshed when retrieving profiles with &lt;code&gt;include&#x3D;accessible&lt;/code&gt;.</value>
        [DataMember(Name = "image_url", EmitDefaultValue = false)]
        public string ImageUrl { get; private set; }

        /// <summary>
        /// Returns false as ImageUrl should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeImageUrl()
        {
            return false;
        }
        /// <summary>
        /// The social network this profile belongs to.
        /// </summary>
        /// <value>The social network this profile belongs to.</value>
        /// <example>facebook</example>
        [DataMember(Name = "network", EmitDefaultValue = false)]
        public string Network { get; private set; }

        /// <summary>
        /// Returns false as Network should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNetwork()
        {
            return false;
        }
        /// <summary>
        /// The social network&#39;s reference for this post. Only set when the status is &lt;code&gt;DONE&lt;/code&gt;.
        /// </summary>
        /// <value>The social network&#39;s reference for this post. Only set when the status is &lt;code&gt;DONE&lt;/code&gt;.</value>
        [DataMember(Name = "network_post_id", EmitDefaultValue = false)]
        public string NetworkPostId { get; private set; }

        /// <summary>
        /// Returns false as NetworkPostId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNetworkPostId()
        {
            return false;
        }
        /// <summary>
        /// The permalink URL to the published post on the social network. Only set when the status is &lt;code&gt;DONE&lt;/code&gt;.
        /// </summary>
        /// <value>The permalink URL to the published post on the social network. Only set when the status is &lt;code&gt;DONE&lt;/code&gt;.</value>
        [DataMember(Name = "post_url", EmitDefaultValue = false)]
        public string PostUrl { get; private set; }

        /// <summary>
        /// Returns false as PostUrl should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePostUrl()
        {
            return false;
        }
        /// <summary>
        /// The unique identifier for the profile to post to. Use the &lt;code&gt;profile_id&lt;/code&gt; from &lt;code&gt;GET /social/profiles&lt;/code&gt;.
        /// </summary>
        /// <value>The unique identifier for the profile to post to. Use the &lt;code&gt;profile_id&lt;/code&gt; from &lt;code&gt;GET /social/profiles&lt;/code&gt;.</value>
        [DataMember(Name = "profile_id", IsRequired = true, EmitDefaultValue = true)]
        public string ProfileId { get; set; }

        /// <summary>
        /// The display name of the profile.
        /// </summary>
        /// <value>The display name of the profile.</value>
        [DataMember(Name = "profile_name", EmitDefaultValue = false)]
        public string ProfileName { get; private set; }

        /// <summary>
        /// Returns false as ProfileName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeProfileName()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateSocialPostRequestProfilePostsInnerProfilesInner {\n");
            sb.Append("  AccountUsername: ").Append(AccountUsername).Append("\n");
            sb.Append("  CampaignActivityId: ").Append(CampaignActivityId).Append("\n");
            sb.Append("  CampaignActivityStatus: ").Append(CampaignActivityStatus).Append("\n");
            sb.Append("  CampaignActivityStatusDate: ").Append(CampaignActivityStatusDate).Append("\n");
            sb.Append("  CampaignActivityStatusMessage: ").Append(CampaignActivityStatusMessage).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  NetworkPostId: ").Append(NetworkPostId).Append("\n");
            sb.Append("  PostUrl: ").Append(PostUrl).Append("\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("  ProfileName: ").Append(ProfileName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
