/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// CreateEvent201ResponseEventSettings
    /// </summary>
    [DataContract(Name = "createEvent_201_response_event_settings")]
    public partial class CreateEvent201ResponseEventSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEvent201ResponseEventSettings" /> class.
        /// </summary>
        /// <param name="eventRequiresPayments">Specifies if the event is configured to require payment..</param>
        /// <param name="itemConfigured">Specifies if items exist for the event..</param>
        /// <param name="onlinePaymentConfigured">Specifies if online payment is configured for the event..</param>
        /// <param name="paymentConfigured">Specifies if payment is configured for the event..</param>
        /// <param name="promoCodeConfigured">Specifies if promo code is configured for the event..</param>
        /// <param name="ticketConfigured">Specifies if ticketing is configured for the event.</param>
        public CreateEvent201ResponseEventSettings(bool eventRequiresPayments = default(bool), bool itemConfigured = default(bool), bool onlinePaymentConfigured = default(bool), bool paymentConfigured = default(bool), bool promoCodeConfigured = default(bool), bool ticketConfigured = default(bool))
        {
            this.EventRequiresPayments = eventRequiresPayments;
            this.ItemConfigured = itemConfigured;
            this.OnlinePaymentConfigured = onlinePaymentConfigured;
            this.PaymentConfigured = paymentConfigured;
            this.PromoCodeConfigured = promoCodeConfigured;
            this.TicketConfigured = ticketConfigured;
        }

        /// <summary>
        /// Specifies if the event is configured to require payment.
        /// </summary>
        /// <value>Specifies if the event is configured to require payment.</value>
        /// <example>true</example>
        [DataMember(Name = "event_requires_payments", EmitDefaultValue = true)]
        public bool EventRequiresPayments { get; set; }

        /// <summary>
        /// Specifies if items exist for the event.
        /// </summary>
        /// <value>Specifies if items exist for the event.</value>
        /// <example>false</example>
        [DataMember(Name = "item_configured", EmitDefaultValue = true)]
        public bool ItemConfigured { get; set; }

        /// <summary>
        /// Specifies if online payment is configured for the event.
        /// </summary>
        /// <value>Specifies if online payment is configured for the event.</value>
        /// <example>false</example>
        [DataMember(Name = "online_payment_configured", EmitDefaultValue = true)]
        public bool OnlinePaymentConfigured { get; set; }

        /// <summary>
        /// Specifies if payment is configured for the event.
        /// </summary>
        /// <value>Specifies if payment is configured for the event.</value>
        /// <example>false</example>
        [DataMember(Name = "payment_configured", EmitDefaultValue = true)]
        public bool PaymentConfigured { get; set; }

        /// <summary>
        /// Specifies if promo code is configured for the event.
        /// </summary>
        /// <value>Specifies if promo code is configured for the event.</value>
        /// <example>false</example>
        [DataMember(Name = "promo_code_configured", EmitDefaultValue = true)]
        public bool PromoCodeConfigured { get; set; }

        /// <summary>
        /// Specifies if ticketing is configured for the event
        /// </summary>
        /// <value>Specifies if ticketing is configured for the event</value>
        /// <example>true</example>
        [DataMember(Name = "ticket_configured", EmitDefaultValue = true)]
        public bool TicketConfigured { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateEvent201ResponseEventSettings {\n");
            sb.Append("  EventRequiresPayments: ").Append(EventRequiresPayments).Append("\n");
            sb.Append("  ItemConfigured: ").Append(ItemConfigured).Append("\n");
            sb.Append("  OnlinePaymentConfigured: ").Append(OnlinePaymentConfigured).Append("\n");
            sb.Append("  PaymentConfigured: ").Append(PaymentConfigured).Append("\n");
            sb.Append("  PromoCodeConfigured: ").Append(PromoCodeConfigured).Append("\n");
            sb.Append("  TicketConfigured: ").Append(TicketConfigured).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
