/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.193
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// CreateListDeleteActivity201Response
    /// </summary>
    [DataContract(Name = "createListDeleteActivity_201_response")]
    public partial class CreateListDeleteActivity201Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListDeleteActivity201Response" /> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="links">links.</param>
        public CreateListDeleteActivity201Response(CreateListDeleteActivity201ResponseStatus status = default(CreateListDeleteActivity201ResponseStatus), CreateListDeleteActivity201ResponseLinks links = default(CreateListDeleteActivity201ResponseLinks))
        {
            this.Status = status;
            this.Links = links;
        }

        /// <summary>
        /// The system assigned UUID that uniquely identifies an activity.
        /// </summary>
        /// <value>The system assigned UUID that uniquely identifies an activity.</value>
        /// <example>af86135c-8740-11eb-8abf-fa163ef30864</example>
        [DataMember(Name = "activity_id", EmitDefaultValue = false)]
        public string ActivityId { get; private set; }

        /// <summary>
        /// Returns false as ActivityId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeActivityId()
        {
            return false;
        }
        /// <summary>
        /// The activity processing state.
        /// </summary>
        /// <value>The activity processing state.</value>
        /// <example>initialized</example>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; private set; }

        /// <summary>
        /// Returns false as State should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeState()
        {
            return false;
        }
        /// <summary>
        /// Timestamp showing when processing started for the activity, in ISO-8601 format.
        /// </summary>
        /// <value>Timestamp showing when processing started for the activity, in ISO-8601 format.</value>
        /// <example>2019-12-12T15:38:24Z</example>
        [DataMember(Name = "started_at", EmitDefaultValue = false)]
        public DateTime StartedAt { get; private set; }

        /// <summary>
        /// Returns false as StartedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStartedAt()
        {
            return false;
        }
        /// <summary>
        /// Timestamp showing when processing completed for the activity, in ISO-8601 format.
        /// </summary>
        /// <value>Timestamp showing when processing completed for the activity, in ISO-8601 format.</value>
        /// <example>2019-12-12T15:38:24Z</example>
        [DataMember(Name = "completed_at", EmitDefaultValue = false)]
        public DateTime CompletedAt { get; private set; }

        /// <summary>
        /// Returns false as CompletedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCompletedAt()
        {
            return false;
        }
        /// <summary>
        /// Timestamp showing when the activity was first requested, in ISO-8601 format.
        /// </summary>
        /// <value>Timestamp showing when the activity was first requested, in ISO-8601 format.</value>
        /// <example>2019-12-12T15:38:24Z</example>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Returns false as CreatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return false;
        }
        /// <summary>
        /// Timestamp showing when the activity was last updated, in ISO-8601 format.
        /// </summary>
        /// <value>Timestamp showing when the activity was last updated, in ISO-8601 format.</value>
        /// <example>2019-12-12T15:38:24Z</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; private set; }

        /// <summary>
        /// Returns false as UpdatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return false;
        }
        /// <summary>
        /// The processing percent complete for the activity.
        /// </summary>
        /// <value>The processing percent complete for the activity.</value>
        /// <example>25</example>
        [DataMember(Name = "percent_done", EmitDefaultValue = false)]
        public int PercentDone { get; private set; }

        /// <summary>
        /// Returns false as PercentDone should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePercentDone()
        {
            return false;
        }
        /// <summary>
        /// An array of error message strings describing the errors that occurred.
        /// </summary>
        /// <value>An array of error message strings describing the errors that occurred.</value>
        [DataMember(Name = "activity_errors", EmitDefaultValue = false)]
        public List<string> ActivityErrors { get; private set; }

        /// <summary>
        /// Returns false as ActivityErrors should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeActivityErrors()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public CreateListDeleteActivity201ResponseStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = false)]
        public CreateListDeleteActivity201ResponseLinks Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateListDeleteActivity201Response {\n");
            sb.Append("  ActivityId: ").Append(ActivityId).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  PercentDone: ").Append(PercentDone).Append("\n");
            sb.Append("  ActivityErrors: ").Append(ActivityErrors).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
