/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.193
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// CreateOrUpdateContactRequestStreetAddress
    /// </summary>
    [DataContract(Name = "createOrUpdateContact_request_street_address")]
    public partial class CreateOrUpdateContactRequestStreetAddress : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrUpdateContactRequestStreetAddress" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateOrUpdateContactRequestStreetAddress() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrUpdateContactRequestStreetAddress" /> class.
        /// </summary>
        /// <param name="kind">The type of street address for the contact. Valid values are &lt;code&gt;home&lt;/code&gt;, &lt;code&gt;work&lt;/code&gt;, or &lt;code&gt;other&lt;/code&gt;. (required).</param>
        /// <param name="street">The number and street of the contact&#39;s address..</param>
        /// <param name="city">The name of the city for the contact&#39;s address..</param>
        /// <param name="state">The name of the state or province for the contact&#39;s address..</param>
        /// <param name="postalCode">The zip or postal code for the contact&#39;s address..</param>
        /// <param name="country">The name of the country for the contact&#39;s address..</param>
        public CreateOrUpdateContactRequestStreetAddress(string kind = default(string), string street = default(string), string city = default(string), string state = default(string), string postalCode = default(string), string country = default(string))
        {
            // to ensure "kind" is required (not null)
            if (kind == null)
            {
                throw new ArgumentNullException("kind is a required property for CreateOrUpdateContactRequestStreetAddress and cannot be null");
            }
            this.Kind = kind;
            this.Street = street;
            this.City = city;
            this.State = state;
            this.PostalCode = postalCode;
            this.Country = country;
        }

        /// <summary>
        /// The type of street address for the contact. Valid values are &lt;code&gt;home&lt;/code&gt;, &lt;code&gt;work&lt;/code&gt;, or &lt;code&gt;other&lt;/code&gt;.
        /// </summary>
        /// <value>The type of street address for the contact. Valid values are &lt;code&gt;home&lt;/code&gt;, &lt;code&gt;work&lt;/code&gt;, or &lt;code&gt;other&lt;/code&gt;.</value>
        /// <example>home</example>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public string Kind { get; set; }

        /// <summary>
        /// The number and street of the contact&#39;s address.
        /// </summary>
        /// <value>The number and street of the contact&#39;s address.</value>
        /// <example>1601 Trapelo Rd</example>
        [DataMember(Name = "street", EmitDefaultValue = false)]
        public string Street { get; set; }

        /// <summary>
        /// The name of the city for the contact&#39;s address.
        /// </summary>
        /// <value>The name of the city for the contact&#39;s address.</value>
        /// <example>Waltham</example>
        [DataMember(Name = "city", EmitDefaultValue = false)]
        public string City { get; set; }

        /// <summary>
        /// The name of the state or province for the contact&#39;s address.
        /// </summary>
        /// <value>The name of the state or province for the contact&#39;s address.</value>
        /// <example>Massachusetts</example>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// The zip or postal code for the contact&#39;s address.
        /// </summary>
        /// <value>The zip or postal code for the contact&#39;s address.</value>
        /// <example>02451</example>
        [DataMember(Name = "postal_code", EmitDefaultValue = false)]
        public string PostalCode { get; set; }

        /// <summary>
        /// The name of the country for the contact&#39;s address.
        /// </summary>
        /// <value>The name of the country for the contact&#39;s address.</value>
        /// <example>United States</example>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOrUpdateContactRequestStreetAddress {\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Street: ").Append(Street).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Street (string) maxLength
            if (this.Street != null && this.Street.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Street, length must be less than 255.", new [] { "Street" });
            }

            // City (string) maxLength
            if (this.City != null && this.City.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for City, length must be less than 50.", new [] { "City" });
            }

            // State (string) maxLength
            if (this.State != null && this.State.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for State, length must be less than 50.", new [] { "State" });
            }

            // PostalCode (string) maxLength
            if (this.PostalCode != null && this.PostalCode.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PostalCode, length must be less than 50.", new [] { "PostalCode" });
            }

            // Country (string) maxLength
            if (this.Country != null && this.Country.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Country, length must be less than 50.", new [] { "Country" });
            }

            yield break;
        }
    }

}
