/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// The physical address associated with the account
    /// </summary>
    [DataContract(Name = "EmailCampaignAccountInformation_physical_address")]
    public partial class EmailCampaignAccountInformationPhysicalAddress : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailCampaignAccountInformationPhysicalAddress" /> class.
        /// </summary>
        /// <param name="orgName">Organization name.</param>
        /// <param name="addressLine1">Primary address line.</param>
        /// <param name="addressLine2">Secondary address line.</param>
        /// <param name="addressLine3">Tertiary address line.</param>
        /// <param name="city">City name.</param>
        /// <param name="stateOrProvCode">State or province code.</param>
        /// <param name="stateOrProv">State or province full name.</param>
        /// <param name="stateNonUs">Non-US state designation.</param>
        /// <param name="postalCode">Postal or ZIP code.</param>
        /// <param name="countryCode">ISO country code.</param>
        /// <param name="country">Country full name.</param>
        /// <param name="addressOptional">Optional address field.</param>
        /// <param name="placeHolder">Indicates if this is a placeholder address.</param>
        public EmailCampaignAccountInformationPhysicalAddress(string orgName = default(string), string addressLine1 = default(string), string addressLine2 = default(string), string addressLine3 = default(string), string city = default(string), string stateOrProvCode = default(string), string stateOrProv = default(string), string stateNonUs = default(string), string postalCode = default(string), string countryCode = default(string), string country = default(string), string addressOptional = default(string), bool placeHolder = default(bool))
        {
            this.OrgName = orgName;
            this.AddressLine1 = addressLine1;
            this.AddressLine2 = addressLine2;
            this.AddressLine3 = addressLine3;
            this.City = city;
            this.StateOrProvCode = stateOrProvCode;
            this.StateOrProv = stateOrProv;
            this.StateNonUs = stateNonUs;
            this.PostalCode = postalCode;
            this.CountryCode = countryCode;
            this.Country = country;
            this.AddressOptional = addressOptional;
            this.PlaceHolder = placeHolder;
        }

        /// <summary>
        /// Organization name
        /// </summary>
        /// <value>Organization name</value>
        /// <example>InstaPrinz</example>
        [DataMember(Name = "org_name", EmitDefaultValue = false)]
        public string OrgName { get; set; }

        /// <summary>
        /// Primary address line
        /// </summary>
        /// <value>Primary address line</value>
        /// <example>123 Maple Street</example>
        [DataMember(Name = "address_line_1", EmitDefaultValue = false)]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// Secondary address line
        /// </summary>
        /// <value>Secondary address line</value>
        [DataMember(Name = "address_line_2", EmitDefaultValue = false)]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// Tertiary address line
        /// </summary>
        /// <value>Tertiary address line</value>
        [DataMember(Name = "address_line_3", EmitDefaultValue = false)]
        public string AddressLine3 { get; set; }

        /// <summary>
        /// City name
        /// </summary>
        /// <value>City name</value>
        /// <example>Hagerstown</example>
        [DataMember(Name = "city", EmitDefaultValue = false)]
        public string City { get; set; }

        /// <summary>
        /// State or province code
        /// </summary>
        /// <value>State or province code</value>
        /// <example>MD</example>
        [DataMember(Name = "state_or_prov_code", EmitDefaultValue = false)]
        public string StateOrProvCode { get; set; }

        /// <summary>
        /// State or province full name
        /// </summary>
        /// <value>State or province full name</value>
        [DataMember(Name = "state_or_prov", EmitDefaultValue = false)]
        public string StateOrProv { get; set; }

        /// <summary>
        /// Non-US state designation
        /// </summary>
        /// <value>Non-US state designation</value>
        [DataMember(Name = "state_non_us", EmitDefaultValue = false)]
        public string StateNonUs { get; set; }

        /// <summary>
        /// Postal or ZIP code
        /// </summary>
        /// <value>Postal or ZIP code</value>
        /// <example>21740</example>
        [DataMember(Name = "postal_code", EmitDefaultValue = false)]
        public string PostalCode { get; set; }

        /// <summary>
        /// ISO country code
        /// </summary>
        /// <value>ISO country code</value>
        /// <example>US</example>
        [DataMember(Name = "country_code", EmitDefaultValue = false)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Country full name
        /// </summary>
        /// <value>Country full name</value>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Optional address field
        /// </summary>
        /// <value>Optional address field</value>
        [DataMember(Name = "address_optional", EmitDefaultValue = false)]
        public string AddressOptional { get; set; }

        /// <summary>
        /// Indicates if this is a placeholder address
        /// </summary>
        /// <value>Indicates if this is a placeholder address</value>
        /// <example>false</example>
        [DataMember(Name = "place_holder", EmitDefaultValue = true)]
        public bool PlaceHolder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailCampaignAccountInformationPhysicalAddress {\n");
            sb.Append("  OrgName: ").Append(OrgName).Append("\n");
            sb.Append("  AddressLine1: ").Append(AddressLine1).Append("\n");
            sb.Append("  AddressLine2: ").Append(AddressLine2).Append("\n");
            sb.Append("  AddressLine3: ").Append(AddressLine3).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  StateOrProvCode: ").Append(StateOrProvCode).Append("\n");
            sb.Append("  StateOrProv: ").Append(StateOrProv).Append("\n");
            sb.Append("  StateNonUs: ").Append(StateNonUs).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  AddressOptional: ").Append(AddressOptional).Append("\n");
            sb.Append("  PlaceHolder: ").Append(PlaceHolder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
