/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// Provides information about the event listing.
    /// </summary>
    [DataContract(Name = "EventListingDto")]
    public partial class EventListingDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventListingDto" /> class.
        /// </summary>
        /// <param name="eventId">The unique identifier for the event..</param>
        /// <param name="title">The title of the event..</param>
        /// <param name="description">The description of the event..</param>
        /// <param name="startTime">The start time of the event in UTC format..</param>
        /// <param name="endTime">The end time of the event in UTC format..</param>
        /// <param name="status">The current status of the event..</param>
        /// <param name="registrationUrl">The URL for event registration.</param>
        /// <param name="name">The name of the event..</param>
        /// <param name="eventType">Use to specify the type of event..</param>
        /// <param name="locationType">Specifies if this is a physical or virtual event (of both), or if the location is to be specified in the future..</param>
        /// <param name="timeZoneType">The type of time zone..</param>
        /// <param name="address">address.</param>
        /// <param name="eventRegistrationSummaryMetrics">eventRegistrationSummaryMetrics.</param>
        /// <param name="createTime">The create time of the event in UTC format..</param>
        public EventListingDto(string eventId = default(string), string title = default(string), string description = default(string), string startTime = default(string), string endTime = default(string), string status = default(string), string registrationUrl = default(string), string name = default(string), string eventType = default(string), string locationType = default(string), string timeZoneType = default(string), AddressDto1 address = default(AddressDto1), FindEvents200ResponseRecordsInnerEventRegistrationSummaryMetrics eventRegistrationSummaryMetrics = default(FindEvents200ResponseRecordsInnerEventRegistrationSummaryMetrics), string createTime = default(string))
        {
            this.EventId = eventId;
            this.Title = title;
            this.Description = description;
            this.StartTime = startTime;
            this.EndTime = endTime;
            this.Status = status;
            this.RegistrationUrl = registrationUrl;
            this.Name = name;
            this.EventType = eventType;
            this.LocationType = locationType;
            this.TimeZoneType = timeZoneType;
            this.Address = address;
            this.EventRegistrationSummaryMetrics = eventRegistrationSummaryMetrics;
            this.CreateTime = createTime;
        }

        /// <summary>
        /// The unique identifier for the event.
        /// </summary>
        /// <value>The unique identifier for the event.</value>
        /// <example>05cf4d60-56ea-4023-bf49-b35e56a9c7b5</example>
        [DataMember(Name = "event_id", EmitDefaultValue = false)]
        public string EventId { get; set; }

        /// <summary>
        /// The title of the event.
        /// </summary>
        /// <value>The title of the event.</value>
        /// <example>Class of 2015 Reunion</example>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// The description of the event.
        /// </summary>
        /// <value>The description of the event.</value>
        /// <example>Join us for a night of reminiscing and celebration!</example>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The start time of the event in UTC format.
        /// </summary>
        /// <value>The start time of the event in UTC format.</value>
        /// <example>2023-12-01T20:30:00Z</example>
        [DataMember(Name = "start_time", EmitDefaultValue = false)]
        public string StartTime { get; set; }

        /// <summary>
        /// The end time of the event in UTC format.
        /// </summary>
        /// <value>The end time of the event in UTC format.</value>
        /// <example>2023-12-01T21:30:00Z</example>
        [DataMember(Name = "end_time", EmitDefaultValue = false)]
        public string EndTime { get; set; }

        /// <summary>
        /// The current status of the event.
        /// </summary>
        /// <value>The current status of the event.</value>
        /// <example>ACTIVE</example>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// The URL for event registration
        /// </summary>
        /// <value>The URL for event registration</value>
        /// <example>https://sample_url.com/ev/reg/scrk2u2</example>
        [DataMember(Name = "registration_url", EmitDefaultValue = false)]
        public string RegistrationUrl { get; set; }

        /// <summary>
        /// The name of the event.
        /// </summary>
        /// <value>The name of the event.</value>
        /// <example>Holiday Market at Snowport</example>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Use to specify the type of event.
        /// </summary>
        /// <value>Use to specify the type of event.</value>
        /// <example>PERFORMING_ARTS</example>
        [DataMember(Name = "event_type", EmitDefaultValue = false)]
        public string EventType { get; set; }

        /// <summary>
        /// Specifies if this is a physical or virtual event (of both), or if the location is to be specified in the future.
        /// </summary>
        /// <value>Specifies if this is a physical or virtual event (of both), or if the location is to be specified in the future.</value>
        /// <example>PHYSICAL</example>
        [DataMember(Name = "location_type", EmitDefaultValue = false)]
        public string LocationType { get; set; }

        /// <summary>
        /// The type of time zone.
        /// </summary>
        /// <value>The type of time zone.</value>
        /// <example>EST</example>
        [DataMember(Name = "time_zone_type", EmitDefaultValue = false)]
        public string TimeZoneType { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public AddressDto1 Address { get; set; }

        /// <summary>
        /// Gets or Sets EventRegistrationSummaryMetrics
        /// </summary>
        [DataMember(Name = "event_registration_summary_metrics", EmitDefaultValue = false)]
        public FindEvents200ResponseRecordsInnerEventRegistrationSummaryMetrics EventRegistrationSummaryMetrics { get; set; }

        /// <summary>
        /// The create time of the event in UTC format.
        /// </summary>
        /// <value>The create time of the event in UTC format.</value>
        /// <example>2023-09-01T20:30:00Z</example>
        [DataMember(Name = "create_time", EmitDefaultValue = false)]
        public string CreateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventListingDto {\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RegistrationUrl: ").Append(RegistrationUrl).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  LocationType: ").Append(LocationType).Append("\n");
            sb.Append("  TimeZoneType: ").Append(TimeZoneType).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  EventRegistrationSummaryMetrics: ").Append(EventRegistrationSummaryMetrics).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
