/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.185
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// The cross-referenced pair of V3 API &lt;code&gt;list_id&lt;/code&gt; and V2 API &lt;code&gt;sequence_id&lt;/code&gt; for a list. Response is sorted ascending by &lt;code&gt;sequence_id&lt;/code&gt;.
    /// </summary>
    [DataContract(Name = "getContactIdXrefs_200_response_xrefs_inner")]
    public partial class GetContactIdXrefs200ResponseXrefsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetContactIdXrefs200ResponseXrefsInner" /> class.
        /// </summary>
        /// <param name="sequenceId">The V2 API contact unique identifier.</param>
        /// <param name="contactId">The V3 API contact unique identifier.</param>
        public GetContactIdXrefs200ResponseXrefsInner(string sequenceId = default(string), Guid contactId = default(Guid))
        {
            this.SequenceId = sequenceId;
            this.ContactId = contactId;
        }

        /// <summary>
        /// The V2 API contact unique identifier
        /// </summary>
        /// <value>The V2 API contact unique identifier</value>
        /// <example>0016633325</example>
        [DataMember(Name = "sequence_id", EmitDefaultValue = false)]
        public string SequenceId { get; set; }

        /// <summary>
        /// The V3 API contact unique identifier
        /// </summary>
        /// <value>The V3 API contact unique identifier</value>
        /// <example>ab7ab702-b935-11e9-8a58-fa163e6b01c1</example>
        [DataMember(Name = "contact_id", EmitDefaultValue = false)]
        public Guid ContactId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetContactIdXrefs200ResponseXrefsInner {\n");
            sb.Append("  SequenceId: ").Append(SequenceId).Append("\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
