/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.185
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// GetEmailCampaignXrefs200ResponseXrefsInner
    /// </summary>
    [DataContract(Name = "getEmailCampaignXrefs_200_response_xrefs_inner")]
    public partial class GetEmailCampaignXrefs200ResponseXrefsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailCampaignXrefs200ResponseXrefsInner" /> class.
        /// </summary>
        /// <param name="v2EmailCampaignId">Identifies an email campaign in the V2 API..</param>
        /// <param name="campaignId">&lt;p&gt;Identifies a campaign in the V3 API. In the V3 API, each campaign contains one or more activities. For more information, see &lt;a href&#x3D;\&quot;/api_guide/v3_v2_email_campaign_deltas.html\&quot; target_\&quot;blank\&quot;&gt;V3 Email Campaign Resource Changes&lt;a/&gt;.&lt;p&gt;.</param>
        /// <param name="campaignActivityId">&lt;p&gt;Identifies a campaign activity in the V3 API. In the V3 API, each campaign contains one or more activities. Email type activities represent the detailed information in an email and contain properties like &lt;code&gt;from_email&lt;/code&gt; and &lt;code&gt;from_name&lt;/code&gt;. For more information, see &lt;a href&#x3D;\&quot;/api_guide/v3_v2_email_campaign_deltas.html\&quot; target_\&quot;blank\&quot;&gt;V3 Campaign Resource Changes&lt;a/&gt;.&lt;p&gt;.</param>
        public GetEmailCampaignXrefs200ResponseXrefsInner(string v2EmailCampaignId = default(string), Guid campaignId = default(Guid), Guid campaignActivityId = default(Guid))
        {
            this.V2EmailCampaignId = v2EmailCampaignId;
            this.CampaignId = campaignId;
            this.CampaignActivityId = campaignActivityId;
        }

        /// <summary>
        /// Identifies an email campaign in the V2 API.
        /// </summary>
        /// <value>Identifies an email campaign in the V2 API.</value>
        /// <example>1100567546598</example>
        [DataMember(Name = "v2_email_campaign_id", EmitDefaultValue = false)]
        public string V2EmailCampaignId { get; set; }

        /// <summary>
        /// &lt;p&gt;Identifies a campaign in the V3 API. In the V3 API, each campaign contains one or more activities. For more information, see &lt;a href&#x3D;\&quot;/api_guide/v3_v2_email_campaign_deltas.html\&quot; target_\&quot;blank\&quot;&gt;V3 Email Campaign Resource Changes&lt;a/&gt;.&lt;p&gt;
        /// </summary>
        /// <value>&lt;p&gt;Identifies a campaign in the V3 API. In the V3 API, each campaign contains one or more activities. For more information, see &lt;a href&#x3D;\&quot;/api_guide/v3_v2_email_campaign_deltas.html\&quot; target_\&quot;blank\&quot;&gt;V3 Email Campaign Resource Changes&lt;a/&gt;.&lt;p&gt;</value>
        /// <example>e4cf53f0-e37f-11e8-9f32-f2801f1b9fd1</example>
        [DataMember(Name = "campaign_id", EmitDefaultValue = false)]
        public Guid CampaignId { get; set; }

        /// <summary>
        /// &lt;p&gt;Identifies a campaign activity in the V3 API. In the V3 API, each campaign contains one or more activities. Email type activities represent the detailed information in an email and contain properties like &lt;code&gt;from_email&lt;/code&gt; and &lt;code&gt;from_name&lt;/code&gt;. For more information, see &lt;a href&#x3D;\&quot;/api_guide/v3_v2_email_campaign_deltas.html\&quot; target_\&quot;blank\&quot;&gt;V3 Campaign Resource Changes&lt;a/&gt;.&lt;p&gt;
        /// </summary>
        /// <value>&lt;p&gt;Identifies a campaign activity in the V3 API. In the V3 API, each campaign contains one or more activities. Email type activities represent the detailed information in an email and contain properties like &lt;code&gt;from_email&lt;/code&gt; and &lt;code&gt;from_name&lt;/code&gt;. For more information, see &lt;a href&#x3D;\&quot;/api_guide/v3_v2_email_campaign_deltas.html\&quot; target_\&quot;blank\&quot;&gt;V3 Campaign Resource Changes&lt;a/&gt;.&lt;p&gt;</value>
        /// <example>4c08372c-957a-48b5-bc45-72c7f00796cd</example>
        [DataMember(Name = "campaign_activity_id", EmitDefaultValue = false)]
        public Guid CampaignActivityId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEmailCampaignXrefs200ResponseXrefsInner {\n");
            sb.Append("  V2EmailCampaignId: ").Append(V2EmailCampaignId).Append("\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  CampaignActivityId: ").Append(CampaignActivityId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
