/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// GetRegistrationInfo200ResponseTicketsInner
    /// </summary>
    [DataContract(Name = "getRegistrationInfo_200_response_tickets_inner")]
    public partial class GetRegistrationInfo200ResponseTicketsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetRegistrationInfo200ResponseTicketsInner" /> class.
        /// </summary>
        /// <param name="checkedInTime">The event check in time date, in ISO format..</param>
        /// <param name="editable">Set to &lt;code&gt;true&lt;/code&gt; to allow or &lt;code&gt;false&lt;/code&gt; to not allow registrations to be modified..</param>
        /// <param name="orderTicketKey">The system generated number used to identify a ticket order..</param>
        /// <param name="price">The price for a ticket..</param>
        /// <param name="ticketName">The name used to identify the ticket..</param>
        /// <param name="fields">fields.</param>
        public GetRegistrationInfo200ResponseTicketsInner(DateTime checkedInTime = default(DateTime), bool editable = default(bool), string orderTicketKey = default(string), decimal price = default(decimal), string ticketName = default(string), List<GetRegistrationInfo200ResponseContactInner> fields = default(List<GetRegistrationInfo200ResponseContactInner>))
        {
            this.CheckedInTime = checkedInTime;
            this.Editable = editable;
            this.OrderTicketKey = orderTicketKey;
            this.Price = price;
            this.TicketName = ticketName;
            this.Fields = fields;
        }

        /// <summary>
        /// The event check in time date, in ISO format.
        /// </summary>
        /// <value>The event check in time date, in ISO format.</value>
        /// <example>2025-11-20T16:13:02.072Z</example>
        [DataMember(Name = "checked_in_time", EmitDefaultValue = false)]
        public DateTime CheckedInTime { get; set; }

        /// <summary>
        /// Set to &lt;code&gt;true&lt;/code&gt; to allow or &lt;code&gt;false&lt;/code&gt; to not allow registrations to be modified.
        /// </summary>
        /// <value>Set to &lt;code&gt;true&lt;/code&gt; to allow or &lt;code&gt;false&lt;/code&gt; to not allow registrations to be modified.</value>
        /// <example>false</example>
        [DataMember(Name = "editable", EmitDefaultValue = true)]
        public bool Editable { get; set; }

        /// <summary>
        /// The system generated number used to identify a ticket order.
        /// </summary>
        /// <value>The system generated number used to identify a ticket order.</value>
        /// <example>a1b2c3</example>
        [DataMember(Name = "order_ticket_key", EmitDefaultValue = false)]
        public string OrderTicketKey { get; set; }

        /// <summary>
        /// The price for a ticket.
        /// </summary>
        /// <value>The price for a ticket.</value>
        /// <example>25</example>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public decimal Price { get; set; }

        /// <summary>
        /// The name used to identify the ticket.
        /// </summary>
        /// <value>The name used to identify the ticket.</value>
        /// <example>General Admission</example>
        [DataMember(Name = "ticket_name", EmitDefaultValue = false)]
        public string TicketName { get; set; }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [DataMember(Name = "fields", EmitDefaultValue = false)]
        public List<GetRegistrationInfo200ResponseContactInner> Fields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetRegistrationInfo200ResponseTicketsInner {\n");
            sb.Append("  CheckedInTime: ").Append(CheckedInTime).Append("\n");
            sb.Append("  Editable: ").Append(Editable).Append("\n");
            sb.Append("  OrderTicketKey: ").Append(OrderTicketKey).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  TicketName: ").Append(TicketName).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
