/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// OrderDetailsDto
    /// </summary>
    [DataContract(Name = "OrderDetailsDto")]
    public partial class OrderDetailsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDetailsDto" /> class.
        /// </summary>
        /// <param name="details">details.</param>
        /// <param name="number">The system assigned string value used to identify the event order..</param>
        /// <param name="paymentMethod">The payment method used when the order was placed. Acceptable payment methods include; &#x60;STRIPE&#x60; and &#x60;PAYPAL&#x60;..</param>
        /// <param name="paymentStatus">The event registration payment status. Acceptable values include; &lt;code&gt;PENDING&lt;/code&gt;, &lt;code&gt;PAID&lt;/code&gt;, &lt;code&gt;REFUNDED&lt;/code&gt;, &lt;code&gt;CANCELLED&lt;/code&gt;, &lt;code&gt;FAILED&lt;/code&gt;, &lt;code&gt;CHARGED_BACK&lt;/code&gt;, &lt;code&gt;PENDING&lt;/code&gt;, &lt;code&gt;UNKNOWN&lt;/code..</param>
        /// <param name="paymentTime">Displays the date and time the payment was made, in ISO format..</param>
        /// <param name="paymentTransactionId">The unique ID used to identify a payment transaction..</param>
        /// <param name="ticketsLink">The URL used to access purchased tickets..</param>
        /// <param name="ticketsText">Text that describes the event and ticket information..</param>
        /// <param name="title">The title for the order..</param>
        public OrderDetailsDto(List<GetRegistrationInfo200ResponseOrderSummaryDetailsInner> details = default(List<GetRegistrationInfo200ResponseOrderSummaryDetailsInner>), string number = default(string), string paymentMethod = default(string), string paymentStatus = default(string), string paymentTime = default(string), string paymentTransactionId = default(string), string ticketsLink = default(string), string ticketsText = default(string), string title = default(string))
        {
            this.Details = details;
            this.Number = number;
            this.PaymentMethod = paymentMethod;
            this.PaymentStatus = paymentStatus;
            this.PaymentTime = paymentTime;
            this.PaymentTransactionId = paymentTransactionId;
            this.TicketsLink = ticketsLink;
            this.TicketsText = ticketsText;
            this.Title = title;
        }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [DataMember(Name = "details", EmitDefaultValue = false)]
        public List<GetRegistrationInfo200ResponseOrderSummaryDetailsInner> Details { get; set; }

        /// <summary>
        /// The system assigned string value used to identify the event order.
        /// </summary>
        /// <value>The system assigned string value used to identify the event order.</value>
        /// <example>ZWbsLNGrHT</example>
        [DataMember(Name = "number", EmitDefaultValue = false)]
        public string Number { get; set; }

        /// <summary>
        /// The payment method used when the order was placed. Acceptable payment methods include; &#x60;STRIPE&#x60; and &#x60;PAYPAL&#x60;.
        /// </summary>
        /// <value>The payment method used when the order was placed. Acceptable payment methods include; &#x60;STRIPE&#x60; and &#x60;PAYPAL&#x60;.</value>
        /// <example>STRIPE</example>
        [DataMember(Name = "payment_method", EmitDefaultValue = false)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// The event registration payment status. Acceptable values include; &lt;code&gt;PENDING&lt;/code&gt;, &lt;code&gt;PAID&lt;/code&gt;, &lt;code&gt;REFUNDED&lt;/code&gt;, &lt;code&gt;CANCELLED&lt;/code&gt;, &lt;code&gt;FAILED&lt;/code&gt;, &lt;code&gt;CHARGED_BACK&lt;/code&gt;, &lt;code&gt;PENDING&lt;/code&gt;, &lt;code&gt;UNKNOWN&lt;/code.
        /// </summary>
        /// <value>The event registration payment status. Acceptable values include; &lt;code&gt;PENDING&lt;/code&gt;, &lt;code&gt;PAID&lt;/code&gt;, &lt;code&gt;REFUNDED&lt;/code&gt;, &lt;code&gt;CANCELLED&lt;/code&gt;, &lt;code&gt;FAILED&lt;/code&gt;, &lt;code&gt;CHARGED_BACK&lt;/code&gt;, &lt;code&gt;PENDING&lt;/code&gt;, &lt;code&gt;UNKNOWN&lt;/code.</value>
        /// <example>PENDING</example>
        [DataMember(Name = "payment_status", EmitDefaultValue = false)]
        public string PaymentStatus { get; set; }

        /// <summary>
        /// Displays the date and time the payment was made, in ISO format.
        /// </summary>
        /// <value>Displays the date and time the payment was made, in ISO format.</value>
        /// <example>2025-08-29T14:29:57.712Z</example>
        [DataMember(Name = "payment_time", EmitDefaultValue = false)]
        public string PaymentTime { get; set; }

        /// <summary>
        /// The unique ID used to identify a payment transaction.
        /// </summary>
        /// <value>The unique ID used to identify a payment transaction.</value>
        /// <example>0bbfdf32-0609-4467-ad19-514130f5beaf</example>
        [DataMember(Name = "payment_transaction_id", EmitDefaultValue = false)]
        public string PaymentTransactionId { get; set; }

        /// <summary>
        /// The URL used to access purchased tickets.
        /// </summary>
        /// <value>The URL used to access purchased tickets.</value>
        /// <example>https://lp.constantcontactpages.com/ev/reg/holly/registrations/fg84378c-a92e-41c4-87c2-0383986baaf9/tickets</example>
        [DataMember(Name = "tickets_link", EmitDefaultValue = false)]
        public string TicketsLink { get; set; }

        /// <summary>
        /// Text that describes the event and ticket information.
        /// </summary>
        /// <value>Text that describes the event and ticket information.</value>
        /// <example>Your tickets for access to the Holiday Festival of Lights.</example>
        [DataMember(Name = "tickets_text", EmitDefaultValue = false)]
        public string TicketsText { get; set; }

        /// <summary>
        /// The title for the order.
        /// </summary>
        /// <value>The title for the order.</value>
        /// <example>Holiday Festival of Lights</example>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderDetailsDto {\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  PaymentStatus: ").Append(PaymentStatus).Append("\n");
            sb.Append("  PaymentTime: ").Append(PaymentTime).Append("\n");
            sb.Append("  PaymentTransactionId: ").Append(PaymentTransactionId).Append("\n");
            sb.Append("  TicketsLink: ").Append(TicketsLink).Append("\n");
            sb.Append("  TicketsText: ").Append(TicketsText).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
