/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.221
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// PaginatedRegistrations
    /// </summary>
    [DataContract(Name = "PaginatedRegistrations")]
    public partial class PaginatedRegistrations : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaginatedRegistrations" /> class.
        /// </summary>
        /// <param name="links">links.</param>
        /// <param name="nextCursor">Use to get the next page of results..</param>
        /// <param name="prevCursor">Use to get the previous page of results..</param>
        /// <param name="records">records.</param>
        /// <param name="totalRecords">The total number of resulting records..</param>
        public PaginatedRegistrations(FindRegistrationsUsingGET200ResponseLinks links = default(FindRegistrationsUsingGET200ResponseLinks), string nextCursor = default(string), string prevCursor = default(string), List<FindRegistrationsUsingGET200ResponseRecordsInner> records = default(List<FindRegistrationsUsingGET200ResponseRecordsInner>), int totalRecords = default(int))
        {
            this.Links = links;
            this.NextCursor = nextCursor;
            this.PrevCursor = prevCursor;
            this.Records = records;
            this.TotalRecords = totalRecords;
        }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = false)]
        public FindRegistrationsUsingGET200ResponseLinks Links { get; set; }

        /// <summary>
        /// Use to get the next page of results.
        /// </summary>
        /// <value>Use to get the next page of results.</value>
        [DataMember(Name = "next_cursor", EmitDefaultValue = false)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Use to get the previous page of results.
        /// </summary>
        /// <value>Use to get the previous page of results.</value>
        [DataMember(Name = "prev_cursor", EmitDefaultValue = false)]
        public string PrevCursor { get; set; }

        /// <summary>
        /// Gets or Sets Records
        /// </summary>
        [DataMember(Name = "records", EmitDefaultValue = false)]
        public List<FindRegistrationsUsingGET200ResponseRecordsInner> Records { get; set; }

        /// <summary>
        /// The total number of resulting records.
        /// </summary>
        /// <value>The total number of resulting records.</value>
        /// <example>563</example>
        [DataMember(Name = "total_records", EmitDefaultValue = false)]
        public int TotalRecords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaginatedRegistrations {\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("  PrevCursor: ").Append(PrevCursor).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("  TotalRecords: ").Append(TotalRecords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
