/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.193
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// Specifies client billing plan details including the type of plan, the plan tiers used, the current billing status, and the day of the month that the client is billed. When a client account is first provisioned, the &#x60;plan_type&#x60; defaults to a &#x60;Trial&#x60; account. After you change an account &#x60;billing_status&#x60; from &#x60;Trial&#x60; to any other &#x60;billing_status&#x60;, you cannot change it back to a &#x60;Trial&#x60; account.
    /// </summary>
    [DataContract(Name = "PlanTiersObject")]
    public partial class PlanTiersObject : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanTiersObject" /> class.
        /// </summary>
        /// <param name="planType">The billing plan that is associated with a client&#39;s Constant Contact account. The billing plan determines which Constant Contact product features that the client account can access. If you are not on the latest billing plan, contact the Constant Contact Partner Team. However, older billing plans and &lt;code&gt;plan_type&lt;/code&gt; enum values will continue to be supported. &lt;ul&gt;   &lt;li&gt;&lt;code&gt;TRIAL&lt;/code&gt;: Provides limited product features for a non-billed account and the account has an expiration date.&lt;/li&gt;   &lt;li&gt;&lt;code&gt;BRONZE&lt;/code&gt;: Billable plan that provides basic email and marketing tools.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;SILVER&lt;/code&gt;: Billable plan that provides all features available in the &lt;code&gt;BRONZE&lt;/code&gt; plan, and adds some additional email campaign to features, such as contact segmentation and social media ads integration.&lt;/li&gt;   &lt;li&gt;&lt;code&gt;GOLD&lt;/code&gt;: Billable plan that provides all available product features.&lt;/li&gt; &lt;/ul&gt;.</param>
        /// <param name="currentTiers">Lists the billing plan tiers that are currently associated with a client account..</param>
        /// <param name="billingStatus">The client&#39;s account billing status. When you first create a client account the &lt;code&gt;billing_status&lt;/code&gt; defaults to &lt;code&gt;Trial&lt;/code&gt;. Billing status values include:   &lt;ul&gt;     &lt;li&gt;&lt;code&gt;Trial&lt;/code&gt; - A non-paying trial client account (default value).&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Open&lt;/code&gt; - An active and paying client account.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Canceled&lt;/code&gt; - A canceled client account.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Trial End&lt;/code&gt; - The trial period has ended for this client account.&lt;/li&gt;   &lt;/ul&gt;.</param>
        /// <param name="billingDayOfMonth">This property is required when an account is not set up to use single billing. For trial accounts, the value is initially set to &lt;code&gt;null&lt;/code&gt;. The value can only be changed when changing the &lt;code&gt;plan_type&lt;/code&gt; from a trial account to a different type of plan, otherwise the value you enter is ignored. You can choose to enter a specific day of month or except the default value, which is the day that the &lt;code&gt;plan_type&lt;/code&gt; value changes from a trial account plan to a different plan. Valid &lt;code&gt;billing_day_of_month&lt;/code&gt; values include &lt;code&gt;1&lt;/code&gt; through and including &lt;code&gt;31&lt;/code&gt;..</param>
        public PlanTiersObject(string planType = default(string), List<PlanTiersObjectCurrentTiersInner> currentTiers = default(List<PlanTiersObjectCurrentTiersInner>), string billingStatus = default(string), int billingDayOfMonth = default(int))
        {
            this.PlanType = planType;
            this.CurrentTiers = currentTiers;
            this.BillingStatus = billingStatus;
            this.BillingDayOfMonth = billingDayOfMonth;
        }

        /// <summary>
        /// The billing plan that is associated with a client&#39;s Constant Contact account. The billing plan determines which Constant Contact product features that the client account can access. If you are not on the latest billing plan, contact the Constant Contact Partner Team. However, older billing plans and &lt;code&gt;plan_type&lt;/code&gt; enum values will continue to be supported. &lt;ul&gt;   &lt;li&gt;&lt;code&gt;TRIAL&lt;/code&gt;: Provides limited product features for a non-billed account and the account has an expiration date.&lt;/li&gt;   &lt;li&gt;&lt;code&gt;BRONZE&lt;/code&gt;: Billable plan that provides basic email and marketing tools.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;SILVER&lt;/code&gt;: Billable plan that provides all features available in the &lt;code&gt;BRONZE&lt;/code&gt; plan, and adds some additional email campaign to features, such as contact segmentation and social media ads integration.&lt;/li&gt;   &lt;li&gt;&lt;code&gt;GOLD&lt;/code&gt;: Billable plan that provides all available product features.&lt;/li&gt; &lt;/ul&gt;
        /// </summary>
        /// <value>The billing plan that is associated with a client&#39;s Constant Contact account. The billing plan determines which Constant Contact product features that the client account can access. If you are not on the latest billing plan, contact the Constant Contact Partner Team. However, older billing plans and &lt;code&gt;plan_type&lt;/code&gt; enum values will continue to be supported. &lt;ul&gt;   &lt;li&gt;&lt;code&gt;TRIAL&lt;/code&gt;: Provides limited product features for a non-billed account and the account has an expiration date.&lt;/li&gt;   &lt;li&gt;&lt;code&gt;BRONZE&lt;/code&gt;: Billable plan that provides basic email and marketing tools.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;SILVER&lt;/code&gt;: Billable plan that provides all features available in the &lt;code&gt;BRONZE&lt;/code&gt; plan, and adds some additional email campaign to features, such as contact segmentation and social media ads integration.&lt;/li&gt;   &lt;li&gt;&lt;code&gt;GOLD&lt;/code&gt;: Billable plan that provides all available product features.&lt;/li&gt; &lt;/ul&gt;</value>
        /// <example>GOLD</example>
        [DataMember(Name = "plan_type", EmitDefaultValue = false)]
        public string PlanType { get; set; }

        /// <summary>
        /// Lists the billing plan tiers that are currently associated with a client account.
        /// </summary>
        /// <value>Lists the billing plan tiers that are currently associated with a client account.</value>
        [DataMember(Name = "current_tiers", EmitDefaultValue = false)]
        public List<PlanTiersObjectCurrentTiersInner> CurrentTiers { get; set; }

        /// <summary>
        /// The client&#39;s account billing status. When you first create a client account the &lt;code&gt;billing_status&lt;/code&gt; defaults to &lt;code&gt;Trial&lt;/code&gt;. Billing status values include:   &lt;ul&gt;     &lt;li&gt;&lt;code&gt;Trial&lt;/code&gt; - A non-paying trial client account (default value).&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Open&lt;/code&gt; - An active and paying client account.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Canceled&lt;/code&gt; - A canceled client account.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Trial End&lt;/code&gt; - The trial period has ended for this client account.&lt;/li&gt;   &lt;/ul&gt;
        /// </summary>
        /// <value>The client&#39;s account billing status. When you first create a client account the &lt;code&gt;billing_status&lt;/code&gt; defaults to &lt;code&gt;Trial&lt;/code&gt;. Billing status values include:   &lt;ul&gt;     &lt;li&gt;&lt;code&gt;Trial&lt;/code&gt; - A non-paying trial client account (default value).&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Open&lt;/code&gt; - An active and paying client account.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Canceled&lt;/code&gt; - A canceled client account.&lt;/li&gt;     &lt;li&gt;&lt;code&gt;Trial End&lt;/code&gt; - The trial period has ended for this client account.&lt;/li&gt;   &lt;/ul&gt;</value>
        /// <example>Open</example>
        [DataMember(Name = "billing_status", EmitDefaultValue = false)]
        public string BillingStatus { get; set; }

        /// <summary>
        /// This property is required when an account is not set up to use single billing. For trial accounts, the value is initially set to &lt;code&gt;null&lt;/code&gt;. The value can only be changed when changing the &lt;code&gt;plan_type&lt;/code&gt; from a trial account to a different type of plan, otherwise the value you enter is ignored. You can choose to enter a specific day of month or except the default value, which is the day that the &lt;code&gt;plan_type&lt;/code&gt; value changes from a trial account plan to a different plan. Valid &lt;code&gt;billing_day_of_month&lt;/code&gt; values include &lt;code&gt;1&lt;/code&gt; through and including &lt;code&gt;31&lt;/code&gt;.
        /// </summary>
        /// <value>This property is required when an account is not set up to use single billing. For trial accounts, the value is initially set to &lt;code&gt;null&lt;/code&gt;. The value can only be changed when changing the &lt;code&gt;plan_type&lt;/code&gt; from a trial account to a different type of plan, otherwise the value you enter is ignored. You can choose to enter a specific day of month or except the default value, which is the day that the &lt;code&gt;plan_type&lt;/code&gt; value changes from a trial account plan to a different plan. Valid &lt;code&gt;billing_day_of_month&lt;/code&gt; values include &lt;code&gt;1&lt;/code&gt; through and including &lt;code&gt;31&lt;/code&gt;.</value>
        /// <example>15</example>
        [DataMember(Name = "billing_day_of_month", EmitDefaultValue = false)]
        public int BillingDayOfMonth { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlanTiersObject {\n");
            sb.Append("  PlanType: ").Append(PlanType).Append("\n");
            sb.Append("  CurrentTiers: ").Append(CurrentTiers).Append("\n");
            sb.Append("  BillingStatus: ").Append(BillingStatus).Append("\n");
            sb.Append("  BillingDayOfMonth: ").Append(BillingDayOfMonth).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
