/*
 * Constant Contact API v3
 *
 * Swagger build version 3.0.62
 *
 * The version of the OpenAPI document: 1.0.185
 * Contact: webservices@constantcontact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ConstantContactApi.Client.OpenAPIDateConverter;

namespace ConstantContactApi.Model
{
    /// <summary>
    /// Tags
    /// </summary>
    [DataContract(Name = "Tags")]
    public partial class Tags : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Tags" /> class.
        /// </summary>
        /// <param name="varTags">Lists all tags and provides tag details..</param>
        /// <param name="links">links.</param>
        public Tags(List<GetTag200Response> varTags = default(List<GetTag200Response>), GetAllTags200ResponseLinks links = default(GetAllTags200ResponseLinks))
        {
            this.VarTags = varTags;
            this.Links = links;
        }

        /// <summary>
        /// Lists all tags and provides tag details.
        /// </summary>
        /// <value>Lists all tags and provides tag details.</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<GetTag200Response> VarTags { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = false)]
        public GetAllTags200ResponseLinks Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Tags {\n");
            sb.Append("  VarTags: ").Append(VarTags).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
