openapi: 3.0.0
info:
  contact:
    email: webservices@constantcontact.com
    name: Constant Contact Public API
  description: Swagger build version 3.0.62
  license:
    name: Private
  title: Constant Contact API v3
  version: 1.0.185
servers:
- url: https://api.cc.email/v3
tags:
- description: Use the account endpoints and methods to get account information.
  name: Account Services
- description: "Bulk activities endpoints are used to manage large numbers of contacts,\
    \ lists, and tags."
  name: Bulk Activities
- description: "Endpoints and methods to get, create, delete, and update one or more\
    \ contacts."
  name: Contacts
- description: "Endpoints and methods to get, create, delete, and update one or more\
    \ contact lists."
  name: Contact Lists
- description: "Endpoints and methods to get, create, delete, and update one or more\
    \ contact tags."
  name: Contact Tags
- description: Contact reporting endpoints are used to gather activity reports for
    campaigns sent to a contact.
  name: Contacts Reporting
- description: "Endpoints and methods to get, create, delete, and update on one or\
    \ more custom fields."
  name: Contacts Custom Fields
- description: "Use email campaign endpoints and methods to get, create, and update\
    \ email campaigns."
  name: Email Campaigns
- description: "Use email campaigns A/B Test endpoints and methods to get, create,\
    \ delete and update A/B tests."
  name: Email Campaigns AB Tests
- description: Use the email reporting endpoints and methods to get reporting data
    for email campaigns you sent to contacts.
  name: Email Reporting
- description: "Use email scheduling endpoints and methods to schedule an email campaign\
    \ activity, unschedule an email campaign activity, and GET schedule information."
  name: Email Scheduling
- description: Use segments to target a subset of your contacts that are most likely
    to engage with a particular campaign.
  name: Segments
- description: Use landing pages reporting endpoints and methods to get reporting
    data about how a contact interacted with a campaign activity.
  name: Landing Pages Reporting
- description: Use SMS reporting endpoints and methods to get reporting data about
    SMS campaigns.
  name: SMS Reporting
- description: Use partner endpoints to manage client Constant Contact accounts under
    your partner account.
  name: Technology Partners
- description: Use partner webhooks to subscribe to billing event notifications from
    Constant Contact.
  name: Technology Partners Webhooks
- description: Endpoints and methods used for integrations.
  name: Integrations
paths:
  /account/user/privileges:
    get:
      description: "Use this method to return the user privileges associated with\
        \ your access token as an array of objects. This method returns all user privileges,\
        \ including privileges the V3 API does not currently use. Constant Contact\
        \ requires specific user privileges to make requests using the V3 API. For\
        \ more information, see the [User Privileges and Roles Overview](/api_guide/user_privileges.html)."
      operationId: getUserPrivileges
      security:
      - oauth2_implicit: []
      - oauth2_access_code: []
      summary: GET User Privileges
      tags:
      - Account Services
  /account/summary:
    get:
      description: "Get account related details for a Constant Contact user account.\
        \ Use the `extra_fields` query parameter to include the `company_logo` and/or\
        \ `physical_address` details in the response body. For more details, see [Get\
        \ Account Summary Details](/api_guide/account_details_get.html)."
      operationId: getAccountDetails
      security:
      - oauth2_implicit:
        - account_read
      - oauth2_access_code:
        - account_read
      summary: GET a Summary of Account Details
      tags:
      - Account Services
      x-authorization-privileges:
      - account:read
      x-sdk-methodName: getAccountDetails
    put:
      description: "Use this method to update account details for a Constant Contact\
        \ account, such as the email address or phone number. This PUT method provides\
        \ a partial update where only valid properties that you include in the request\
        \ body are updated and excluded properties are not overwritten. For more details,\
        \ see [Put (update) Account Summary Details](/api_guide/account_details_put.html)."
      operationId: updateAccount
      security:
      - oauth2_implicit:
        - account_update
      - oauth2_access_code:
        - account_update
      summary: PUT (update) Account Details
      tags:
      - Account Services
      x-authorization-privileges:
      - account:update
      x-sdk-methodName: updateAccount
  /account/summary/physical_address:
    get:
      description: Use this method to get the address where the account's organization
        physically resides. The physical address is required to send emails and displays
        on the footer of every email that is sent from the account.
      operationId: getAccountPhysicalAddress
      security:
      - oauth2_implicit:
        - account_read
      - oauth2_access_code:
        - account_read
      summary: GET the Physical Address for the Account
      tags:
      - Account Services
      x-authorization-privileges:
      - account:read
      x-sdk-methodName: getAccountPhysicalAddress
    post:
      description: "Use this method to add the address where the account's organization\
        \ physically resides. The physical address is required to send emails and\
        \ displays on the footer of every email that is sent from the account. The\
        \ country (<code>country_code</code>) where the account organization resides\
        \ determines whether you use the <code>state_code</code> to specify United\
        \ States (<code>US</code>) and Canada (<code>CA</code>) addresses, or use\
        \ the <code>state_name</code> to specify all other countries."
      operationId: addPhysicalAddress
      security:
      - oauth2_implicit:
        - account_update
      - oauth2_access_code:
        - account_update
      summary: POST the Physical Address for the Account
      tags:
      - Account Services
      x-authorization-privileges:
      - account:update
    put:
      description: "Use this method to update the organization's physical address\
        \ for the Constant Contact user account. The physical address is required\
        \ to send emails and displays on the footer of every email that is sent from\
        \ the account. To get the current physical address, make a GET call to `/account/summary/physical_address`.\
        \ The country (<code>country_code</code>) where the account organization resides\
        \ determines whether you use the <code>state_code</code> to specify United\
        \ States (<code>US</code>) and Canada (<code>CA</code>) addresses, or use\
        \ the <code>state_name</code> to specify all other countries. For more details,\
        \ see [Put (update) the Physical Address for the Account](/api_guide/account_address_put.html).\
        \ You must have the role of Account Owner assigned to update account level\
        \ details. "
      operationId: updateAccountPhysicalAddress
      security:
      - oauth2_implicit:
        - account_update
      - oauth2_access_code:
        - account_update
      summary: PUT (update) the Physical Address for an Account
      tags:
      - Account Services
      x-authorization-privileges:
      - account:update
      x-sdk-methodName: updateAccountPhysicalAddress
  /account/emails:
    get:
      description: "Use this method to return a collection of email addresses for\
        \ the account associated with your access token. When you <a href=\"https://v3.developer.constantcontact.com/api_reference/index.html#!/Email_Campaigns/createEmailCampaignUsingPOST\"\
        \ target=\"_blank\">Create an Email Campaign<a/>, you must use an account\
        \ email address with a `CONFIRMED` status in the email campaign `from_email`\
        \ and `reply_to_email` headers.\n      \n\nUse the query parameters to filter\
        \ results. You can filter using `confirm_status`, `role_code`, or `email_address`.\
        \ For example, searching with `confirm_status=CONFIRMED` returns all confirmed\
        \ email addresses in the account. This method only supports one query parameter\
        \ at a time.\n"
      operationId: getAllAccountEmailAddresses
      security:
      - oauth2_implicit:
        - account_read
      - oauth2_access_code:
        - account_read
      summary: GET a Collection of Account Email Addresses
      tags:
      - Account Services
      x-authorization-privileges:
      - account:read
      x-sdk-methodName: getAllAccountEmailAddresses
    post:
      description: "Use this method to add a new email address to a Constant Contact\
        \ account. If the email address you are adding already exists in the account\
        \ the API will return a 409 conflict error. \n\nWhen you add a new email address\
        \ to an account, Constant Contact automatically sends an email to that address\
        \ with a link to confirm it. After a user clicks that link, the account email\
        \ status changes from `UNCONFIRMED` to `CONFIRMED`. You can use confirmed\
        \ account email addresses in the email campaign `from_email` and `reply_to_email`\
        \ headers. For more use case information, see [Add an Account Email Address](/api_guide/account_post_emails.html)\
        \ in the API guide. \n"
      operationId: addAccountEmailAddress
      security:
      - oauth2_implicit:
        - account_update
      - oauth2_access_code:
        - account_update
      summary: POST Add an Account Email Address
      tags:
      - Account Services
      x-authorization-privileges:
      - account:update
  /activities:
    get:
      description: "This endpoint returns a collection of activities. Use the state\
        \ query parameter to include only activities with a specific status (processing,\
        \ completed, cancelled, failed, or time_out). Use the limit query parameter\
        \ to define the number of activities returned per page. Learn [more](/api_guide/activity_status.html)."
      operationId: getAllActivities
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Activity Status Collection
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: getAllActivities
  /activities/{activity_id}:
    get:
      description: This endpoint returns an activity status report.
      operationId: getActivityById
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET an Activity Status
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: getActivityById
  /activities/contact_exports:
    post:
      description: "Use this method to create an activity that exports contacts and\
        \ contact details to a CSV file.  You can choose to export all contacts in\
        \ your account (default) or you can use parameters to filter on which contacts\
        \ to export. After Constant Contact finishes processing the activity, use\
        \ the `results` link in the response body to retrieve the CSV file."
      operationId: createExportActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Export Contacts to a File
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createExportActivity
  /contact_exports/{file_export_id}:
    get:
      description: "Use this endpoint to retrieve (GET) a CSV file containing exported\
        \ contacts by providing the `activity_id` of a completed CSV export activity.\
        \ \n"
      operationId: getCSVExportFile
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Retrieve Exported Contacts File
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: getCSVExportFile
  /activities/contact_delete:
    post:
      description: "Use this endpoint to bulk delete contacts in an account. Contacts\
        \ to delete are specified by contact_id (up to 500), or by list_id (up to\
        \ 50 lists); all contacts that are members of the list_ids are deleted. Deleted\
        \ contacts won’t receive email from you, and they don’t count as active contacts.\
        \ Unlike unsubscribed contacts, deleted contacts can be added back to an account.\
        \ [Learn how to revive deleted contacts](/api_guide/contacts_delete.html#revive)."
      operationId: createDeleteActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Delete Contacts in Bulk
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createDeleteActivity
  /activities/contacts_file_import:
    post:
      description: "This multipart method creates an asynchronous background job that\
        \ adds or updates contacts by importing a CSV file containing contact information.\
        \ Do not use a Content-Type header value with this method.\n\nImporting a\
        \ new contact email address automatically sets the contact's `permission_to_send`\
        \ property as `implicit` and the `opt_in_source` property as `Account`. Importing\
        \ an existing contact only updates the contact properties you include in the\
        \ request.\nImporting contacts with `sms_number`s requires using the `sms_permission_to_send`\
        \ parameter  to specify permissions for all contacts being imported. Set to\
        \ `explicit` to specify that all contacts either provided explicit permission.\
        \ Set to `not_set` if permission was not provided. If `explicit`, you must\
        \ also include the `sms_consent_date` as a column header to include the date\
        \ the contact consented to receiving SMS messages.\nContacts must have either\
        \ an email address or an SMS number defined.\n \nThe CSV file has a maximum\
        \ of 40,000 lines including the header row (39,999 contacts) and a maximum\
        \ file size of 4 megabytes (MB).  Lines above the 40,000 line maximum are\
        \ not processed. If the request body exceeds 4 MB, only the contacts contained\
        \ in the first 4 MB are imported and the remaining data is dropped."
      operationId: createCSVImportActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Import Contacts using a CSV File
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createCSVImportActivity
  /activities/contacts_json_import:
    post:
      description: "Use this method to create an asynchronous background job that\
        \ adds new contacts or updates existing contacts by importing a JSON payload.\
        \ This method requires a request body that contains the contact data you are\
        \ importing and the contact lists to which you want to add the imported contacts.\
        \ A contact's data must include an `email` address and/or `sms_number`. The\
        \ `sms_number` must be a US phone number to associate with the contact's SMS-enabled\
        \ phone. Valid formats are <code>1231231234</code> or <code>123-123-1234</code>\
        \ (the country code must be valid).\n\nImporting a new contact using this\
        \ method automatically sets the contact's email `permission_to_send` property\
        \ to `implicit` and the `opt_in_source` property as `Account`. Importing an\
        \ existing contact only updates the contact properties you include in the\
        \ request. For each contact, you can import up to three addresses and three\
        \ phone numbers. International phone numbers are currently not supported.\
        \      \n\nTo import custom fields, prefix the custom field name with `cf:`\
        \ and add it as a contact property. For example, use the property name `cf:first_name`\
        \ if you have a custom field named `first_name`. The custom field must already\
        \ exist in the Constant Contact account you are using. Each contact can contain\
        \ up to 25 custom fields.\n\nTo include a contact's `sms_number`, if the contact\
        \ provided explicit permission to receive SMS messages, you must set the `sms_permission_to_send`\
        \ property to `explicit` and specify the date of consent using the `sms_consent_date`\
        \ column header. If explicit permission was not provided, set `sms_permission_to_send`\
        \ to `not_set` (the `sms_consent_date` is not required). If the `sms_consent_date`\
        \ is not set, SMS messages cannot be sent to contacts and `sms_permission_to_send`\
        \ defaults to `not_set`. Valid value formats for `sms_consent_date` include\
        \ MM/DD/YYYY, M/D/YYYY, YYYY/MM/DD, YYYY/M/D, YYYY-MM-DD, YYYY-M-D,M-D-YYYY,\
        \ or M-DD-YYYY. \n\nThe request body payload has a maximum size of 4 megabytes\
        \ (MB). If the request body exceeds 4 MB, this method only imports the first\
        \ 4 MB and drops the remaining data. Use the activity URL to check the status\
        \ of the import activity request."
      operationId: createImportJSONActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Import Contacts using a JSON Payload
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createImportJSONActivity
  /activities/remove_list_memberships:
    post:
      description: "Use this method to create an activity that removes contacts from\
        \ one or more contact lists. Use the properties in the `source` object to\
        \ remove specific contacts from your lists. Use the `list_ids` array to specify\
        \ the target lists from which contacts are removed. Optionally, if the source\
        \ is  `all_active_contacts` (billable) or `list_ids`, use the `exclude` object\
        \ to exclude specific contacts from being removed from the destination lists."
      operationId: createListRemoveActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Remove Contacts from Lists
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createListRemoveActivity
  /activities/add_list_memberships:
    post:
      description: Use this method to create an activity that adds contacts to one
        or more lists. Each contact can be a member of up to 50 lists. Use the properties
        in the `source` object to specify the contacts you want to add to lists. Use
        the `list_ids` array to specify which lists you want to add your source contacts
        to.
      operationId: createListAddActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Add Contacts to Lists
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createListAddActivity
  /activities/list_delete:
    post:
      description: 'Use this endpoint to delete up to 100 contact lists in an account. '
      operationId: createListDeleteActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Delete Contact Lists
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createListDeleteActivity
  /activities/contacts_taggings_remove:
    post:
      description: |-
        Use this method to create an asynchronous activity that removes one or more tags from all contacts meeting your contact filtering criteria. Filtering criteria must include the `source` type used to identify contacts from which the specified tags (`tag_id`) are removed.
        Source types are mutually exclusive. If the specified source is either `all_active_contacts` or `list_ids`, you can optionally choose to `exclude` specified contacts by `contact_id`. Use the activity link in the results to check the status of your request."
        For more use case information, see "[Remove Tags from Contacts](/api_guide/remove_tagging_activity.html)
      operationId: createTagRemoveActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Remove Tags from Contacts
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createTagRemoveActivity
  /activities/contacts_taggings_add:
    post:
      description: |-
        Use this method to create an asynchronous activity that adds one or more tags to all contacts meeting your contact filtering criteria. Use the `source` type to identify contacts from which the specified tags (`tag_id`) are added.
        Source criteria are mutually exclusive. If the source is `all_active_contacts` or `list_ids`, you can optionally choose to `exclude` contacts by `contact_id`. Use the activity link in the results to check the status of your request.
        For more use case information, see "[Add Tags to Contacts](/api_guide/add_tagging_activity.html)
      operationId: createTagAddContactActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Add Tags to Contacts
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createTagAddContactActivity
  /activities/contacts_tags_delete:
    post:
      description: Use this method to create an asynchronous activity that deletes
        up to 500 tags. Deleted tags are automatically removed from tagged contacts.
        Use the `tag_ids` array of string values in the request body to specify which
        tags to delete.
      operationId: createTagDeleteActivity
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Delete Tags
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createTagDeleteActivity
  /activities/custom_fields_delete:
    post:
      description: 'Use this endpoint to delete up to 100 custom fields for an account. '
      operationId: postCustomFieldDelete
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Delete Custom Fields
      tags:
      - Bulk Activities
      x-authorization-privileges:
      - contacts:write
  /segments:
    get:
      description: "Use this method to get a list of all segments associated with\
        \ the account. You can sort segment results and limit the number of segments\
        \ that display per page. Deleted segments are excluded from the results. For\
        \ more use case information, see [Get All Segments](/api_guide/segment_get_all.html)\
        \ in the API guide."
      operationId: getAllSegments
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET all Segments
      tags:
      - Segments
      x-authorization-privileges:
      - contacts:lists:read
      x-sdk-methodName: getAllSegments
    post:
      description: |-
        Use this method to create a new segment. You create segments to target a subset of your contacts that meet your specific criteria for a marketing campaign. The segment `name` must be unique. The `segment_criteria` requires single-string escaped JSON. Constant Contact uses the contact data that you specify in the `segment_criteria` to evaluate and identify the contacts you want to target. Contact data can be grouped from different data sources, including:

          -  **`tracking`**: Supports **or** and **and** groups.


          -  **`contact`**: Supports **or** and **and** groups.


          -  **`list_membership`**: Supports **or** groups.

          -  **`tags`**: Supports **or** groups.

        If you do not specify `list_membership` as criteria, Constant Contact evaluates all contacts in your account. To avoid returning a 400 error response, when specifying the `segment_criteria` do not request more than 500 email campaigns or a date range greater than 1825 days (5 years) be evaluated.

        For more use case information, see the [Segments Overview](/api_guide/segments_overview.html) in the API guide.
      operationId: createSegment
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: POST (create) a Segment
      tags:
      - Segments
      x-authorization-privileges:
      - contacts:lists:write
  /segments/{segment_id}:
    delete:
      description: |-
        Use this method to delete a segment from your account. Before deleting a segment, verify that the segment is not associated with a scheduled campaign.

        Deleted segments do not display in the results when using the `GET /segments` endpoint. If you know the `segment_id`, you can use the `GET /segments/{segment_id}` endpoint to view the deleted segment's details. A segment's details are preserved for external reference purposes, such as displaying the segment name in a campaign's history. For more use case information, see [Delete a Segment](/api_guide/segment_delete.html) in the API guide.
      operationId: deleteSegment
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: DELETE a Segment
      tags:
      - Segments
      x-authorization-privileges:
      - contacts:lists:write
    get:
      description: "Use this method to get details about a segment, including the\
        \ segment criteria. If you know the `segment_id` You can also use this method\
        \ to get details about a deleted segment. For more use case information, see\
        \ [Get a Segment's Details](/api_guide/segment_get.html) in the API guide."
      operationId: getSegmentById
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET a Segment's Details
      tags:
      - Segments
      x-authorization-privileges:
      - contacts:lists:read
      x-sdk-methodName: getSegmentById
    put:
      description: "Use this method to update an existing segment's name (`name`)\
        \ and/or contact selection criteria (`segment_criteria`). You must specify\
        \ both the `name` and the `segment_criteria` in the request body, even if\
        \ you don't plan to update both. The segment's name must be unique and the\
        \ JSON must be valid (requires single-string escaped JSON). To avoid returning\
        \ a 400 error response, when specifying the `segment_criteria` do not request\
        \ more than 500 email campaigns or a date range greater than 1825 days (5\
        \ years) be evaluated. For more use case information, see [Update Segment\
        \ Details](/api_guide/segment_update.html) in the API guide."
      operationId: updateSegment
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PUT (update) a Segment
      tags:
      - Segments
      x-authorization-privileges:
      - contacts:lists:write
  /segments/{segment_id}/name:
    patch:
      description: "Use this method to update an existing segment `name` with a new\
        \ unique name in the request body. For more use case information, see [Rename\
        \ a Segment](/api_guide/segment_rename.html) in the API guide."
      operationId: updateSegmentName
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PATCH (rename) a Segment
      tags:
      - Segments
      x-authorization-privileges:
      - contacts:lists:write
  /contacts/{contact_id}:
    delete:
      description: "Deletes the contact identified by the contact_id path parameter.\
        \ Deleted contacts won't receive email from you, and they don't count as active\
        \ contacts. Unlike unsubscribed contacts, deleted contacts can be revived,\
        \ or added back to an account. Learn how to [revive deleted contacts](/api_guide/contacts_delete.html#revive)."
      operationId: deleteContact
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: DELETE a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:write
    get:
      description: This endpoint GETs a specific contact resource (contact_id). Use
        the `include` query parameter to add any of the available contact sub-resources
        to the response payload.
      operationId: getContactById
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:read
      x-sdk-methodName: getContactById
    put:
      description: "The PUT method updates an existing contact. You must include the\
        \ `update_source` property in the PUT request payload. To restore  a deleted\
        \ contact you must specify the `update_source` as `Account`. When updating\
        \ any resource using PUT, all properties are updated, overwriting all previous\
        \ values. Any properties left blank or not included in the request are overwritten\
        \ with null value - however this does not apply to contact subresources. \n\
        \nAdd or change any of the subresources by including them in the PUT request\
        \ payload. Omitted subresources are not overwritten with null. If the contact\
        \ being updated is deleted, the contact will be revived.\nIf `email_address`\
        \ is specified: <div class=\"Msg\"><p class=\"note-text\"> **Only use this\
        \ method when a contact gives you their explicit permission to send them an\
        \ email. It is a violation of anti-spam and telemarketing laws, as well as\
        \ a serious violation of the Constant Contact Terms of Service to use the\
        \ Opt-in features of the API to opt a contact back in without his or her own\
        \ action and consent.</p></div>\n\nIf `sms_channel` is specified: <div class=\"\
        Msg\"><p class=\"note-text\">Only use this method when a contact gives you\
        \ their explicit permission to send them an SMS. It is a violation of anti-spam\
        \ and telemarketing laws, as well as a serious violation of the Constant Contact\
        \ Terms of Service to use the Opt-in features of the API to opt a contact\
        \ back in without his or her own action and consent.</p></div>"
      operationId: updateContact
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PUT (update) a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: updateContact
  /contacts:
    get:
      description: |-
        Use this method to return a collection of contacts. Use the query parameters to search for contacts that match specific contact properties and sub-resource properties as criteria. For example, you can search using the contact's `email` address, `lists` memberships, and by the date range that a contact was created or updated. Use the `limit` query parameter to limit the number of results returned per page. Use the `include` query parameter to include contact sub-resources in the response [...]

        By default, this method returns all contacts that are not deleted. Use the `status` query parameter with the value `all` to return all contacts including deleted contacts.
      operationId: getAllContacts
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Contacts Collection
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:read
      x-sdk-methodName: getAllContacts
    post:
      description: |2-

        Creates a new contact resource. You must include the `create_source` property and at least one of the following properties: `first_name`, `last_name`, a unique `email_address` (specified using the `EmailAddress` object), or the `sms_channel` property (specified using the `ContactSmsChannel` object).

        <div class="Msg"><p class="note-text">If `email_address` is specified: **Only use this method when a contact gives you their explicit permission to send them an email. It is a violation of anti-spam and telemarketing laws, as well as a serious violation of the Constant Contact Terms of Service to use the Opt-in features of the API to opt a contact back in without his or her own action and consent.</p></div>

        If `sms_channel` is specified: <div class="Msg"><p class="note-text">Only use this method when a contact gives you their explicit permission to send them an SMS. It is a violation of anti-spam and telemarketing laws, as well as a serious violation of the Constant Contact Terms of Service to use the Opt-in features of the API to opt a contact back in without his or her own action and consent.</p></div>
      operationId: createContact
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: POST (create) a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:write
  /contacts/sign_up_form:
    post:
      description: "Use this method to create a new contact or update an existing\
        \ contact. In the request body, this method requires including the `list_memberships`\
        \ array as well as either the contact's `email_address` string or `sms_channel`\
        \ object which includes the contact's SMS number. The information you specify\
        \ determines if a new contact is either created (the email address or SMS\
        \ number does not already exist in the account), or if an existing contact\
        \ is updated (the email address or SMS number already exists). The SMS product\
        \ feature does not need to be enabled to include a contacts SMS details.\n\
        \nUpdates to existing contacts are partial updates. This method only updates\
        \ the contact properties you include in the request body. Updates append new\
        \ contact lists or custom fields to the existing `list_memberships` or `custom_fields`\
        \ arrays.\n\nIf `email_address` is specified: <div class=\"Msg\"><p class=\"\
        note-text\">Only use this method when a contact gives you their explicit permission\
        \ to send them an email. It is a violation of anti-spam and telemarketing\
        \ laws, as well as a serious violation of the Constant Contact Terms of Service\
        \ to use the Opt-in features of the API to opt a contact back in without his\
        \ or her own action and consent.</p></div>\n\nIf `sms_channel` is specified:\
        \ <div class=\"Msg\"><p class=\"note-text\">Only use this method when a contact\
        \ gives you their explicit permission to send them an SMS. It is a violation\
        \ of anti-spam and telemarketing laws, as well as a serious violation of the\
        \ Constant Contact Terms of Service to use the Opt-in features of the API\
        \ to opt a contact back in without his or her own action and consent.</p></div>\n\
        \nWhen this method creates a new contact, it returns a 201 response code.When\
        \ this method updates an existing contact, it returns a 200 response code.\
        \ Updating a deleted contact restores the contact.\n\nThe method automatically\
        \ modifies the contact's `permission_to_send` and `opt_in_source` properties\
        \ depending on the [Confirmed Opt-In](https://knowledgebase.constantcontact.com/articles/KnowledgeBase/5533-obtain-permission-to-send-email-campaigns-to-your-contacts-by-using-confirmed-opt-in)\
        \ Constant Contact account setting:\n\nIf Confirmed Opt-in is _enabled_, this\
        \ method automatically sets the `permission_to_send` property as `pending_confirmation`\
        \ for new contacts. If Confirmed Opt-in is _disabled_, this method automatically\
        \ sets the `permission_to_send` property as explicit and the `opt_in_source`\
        \ property as `Contact` for new contacts. Updated contacts have their `permission_to_send`\
        \ property set as explicit.\n      "
      operationId: createOrUpdateContact
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: Create or Update a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:write
  /contacts/contact_id_xrefs:
    get:
      description: |-
        <div class="Msg Msg--warning"><p class="note-text">Use this endpoint to migrate your locally stored V2 contact ids to the new V3 format. Developers are expected to use this endpoint sparingly. This endpoint is NOT intended for regular or repeated use. Constant Contact will eventually deprecate and remove this endpoint.</p></div>

        This GET call retrieves a collection of cross-referenced contact sequence IDs (`id` used in the V2 API) and UUIDs (`contact_id` used in the V3 API). This endpoint is intended for developers who have an existing V2 API integration, and are migrating their users to a new V3 API integration. The V2 and V3 APIs use different resource ID formats. Use the `sequence_ids` query parameter to specify a set of comma delimited V2 contacts ids to cross-referenced with their V3 `contact_ids`. See [Mig[...]
      operationId: getContactIdXrefs
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET a collection of V2 and V3 API contact IDs
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:read
  /contact_custom_fields/{custom_field_id}:
    delete:
      description: This DELETE request deletes a custom_field from the user's account
      operationId: deleteCustomField
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: DELETE a custom_field
      tags:
      - Contacts Custom Fields
      x-authorization-privileges:
      - contacts:write
    get:
      description: "This GET call retrieves a `custom_field` resource, specified by\
        \ `custom_field_id`."
      operationId: getCustomField
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET a custom_field
      tags:
      - Contacts Custom Fields
      x-authorization-privileges:
      - contacts:read
    put:
      description: This PUT request updates an existing `custom_field` object.
      operationId: updateCustomField
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PUT (update) a custom_field
      tags:
      - Contacts Custom Fields
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: updateCustomField
  /contact_custom_fields:
    get:
      description: |-
        This GET request returns all `custom_fields` defined in the user's account.
        <div class="Msg"><p class="note-text">This method does not currently support filtering results using the custom field update date.</p></div>
      operationId: getAllCustomFields
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET custom_fields Collection
      tags:
      - Contacts Custom Fields
      x-authorization-privileges:
      - contacts:read
      x-sdk-methodName: getAllCustomFields
    post:
      description: This POST request adds a new `custom_field` to the user's account.
        A user can configure up to 100 `custom_fields` in their account.
      operationId: createCustomFields
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: POST (create) a custom_field
      tags:
      - Contacts Custom Fields
      x-authorization-privileges:
      - contacts:write
      x-sdk-methodName: createCustomFields
  /contact_lists/{list_id}:
    delete:
      description: "Deletes the specified contact list and its membership. DELETE\
        \ List requests are processed asynchronously, and you can track the status\
        \ of the request by making a GET call to the URI shown in the `_links` property\
        \ in the response."
      operationId: deleteList
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: DELETE a List
      tags:
      - Contact Lists
      x-authorization-privileges:
      - contacts:lists:write
      x-sdk-methodName: deleteList
    get:
      description: Use this method to get details about a specific contact list (`list_id`).
      operationId: getList
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET a List
      tags:
      - Contact Lists
      x-authorization-privileges:
      - contacts:lists:read
    put:
      description: "Updates an existing contact list resource, specified by `list_id`"
      operationId: updateList
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PUT (update) a List
      tags:
      - Contact Lists
      x-authorization-privileges:
      - contacts:lists:write
      x-sdk-methodName: updateList
  /contact_lists:
    get:
      description: |-
        Use this method to return details about all contact lists for the account.
        <div class="Msg"><p class="note-text">This method does not currently support filtering results using the contact list update date.</p></div>
      operationId: getAllLists
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Lists Collection
      tags:
      - Contact Lists
      x-authorization-privileges:
      - contacts:lists:read
      x-sdk-methodName: getAllLists
    post:
      description: Create a new contact list resource
      operationId: createList
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: POST (create) a List
      tags:
      - Contact Lists
      x-authorization-privileges:
      - contacts:lists:write
  /contact_lists/list_id_xrefs:
    get:
      description: |-
        <div class="Msg Msg--warning"><p class="note-text">Use this endpoint to migrate your locally stored V2 contact list data to the new V3 format. Developers are expected to use this endpoint sparingly. This endpoint is NOT intended for regular or repeated use. Constant Contact will eventually deprecate and remove this endpoint.</p></div>

        This GET call retrieves a collection of cross-referenced list sequence IDs (`id` used in the V2 API) and UUIDs (`list_id` used in the V3 API). This endpoint is intended for developers who have an existing V2 API integration, and are migrating their users to a new V3 API integration. The V2 and V3 APIs use different resource ID formats. Use the `sequence_ids` query parameter to specify a set of comma delimited V2 list ids to cross-reference. See [Migrating Apps and Data to V3](/api_guide/[...]"
      operationId: getListIdXrefs
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET a collection of V2 and V3 API List IDs
      tags:
      - Contact Lists
      x-authorization-privileges:
      - contacts:lists:read
  /contacts/sms_engagement_history/{contact_id}:
    get:
      description: "Use this method to return SMS engagement details for a contact,\
        \ such as SMS consent and advertising frequency details."
      operationId: getSmsEngagementHistory
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET SMS Engagement History for a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:read
  /contacts/counts:
    get:
      description: "Use to get the total contacts count for the account and the total\
        \ contact-consent counts for each consent state. Optionally, to include the\
        \ total number of contacts that subscribed within the last 30 days in the\
        \ results, use `new_subscribers` in the `include` query parameter. To optimize\
        \ open rates, reduce spam reports, and help grow your business,  you must\
        \ value your contact's consent to receive or to not receive your emails."
      operationId: getContactCounts
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Contact Consent Counts
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:read
      x-sdk-methodName: getContactCounts
  /contacts/resubscribe/{contact_id}:
    put:
      description: 'Use this endpoint to send a confirmation resubscribe email to
        a contact in order to get their confirmation to resubscribe. This endpoint
        also adds the resubscribed contact to the contact lists you specify in the
        request body. You can only send a resubscribe email to the unsubscribed contact
        once. The contact is not resubscribed until after you receive their confirmation. '
      operationId: resubscribeContact
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PUT Resubscribe a Contact
      tags:
      - Contacts
      x-authorization-privileges:
      - contacts:write
  /contact_tags/{tag_id}:
    delete:
      description: "Use this method to create an activity used to un-assign a tag\
        \ from all assigned contacts and delete the tag. This is an asynchronous activity.\
        \ To view activity details for the delete request, use the href link returned\
        \ in the response. [Learn more](/api_guide/tags_delete.html)."
      operationId: deleteTag
      security:
      - oauth2_implicit:
        - contact_data
        oauth2_access_code:
        - contact_data
      summary: DELETE a Tag
      tags:
      - Contact Tags
      x-authorization-privileges:
      - contacts:write
    get:
      description: "Use this method to get tag details for a specified `tag_id`. Use\
        \ the `include_count` query parameter to include or exclude the total number\
        \ of contacts to which this tag is assigned. To learn more, see  [Get a Tag's\
        \ Details](/api_guide/tags_get_single.html)."
      operationId: getTag
      security:
      - oauth2_implicit:
        - contact_data
        oauth2_access_code:
        - contact_data
      summary: GET Tag Details
      tags:
      - Contact Tags
      x-authorization-privileges:
      - contacts:read
    put:
      description: "Use this method to rename an existing tag to a new unique tag\
        \ name (`name`). The maximum length is 255 characters. The `tag_source` value\
        \ cannot be updated using this method. You can set the `tag_source` value\
        \ using the `POST contact_tags method`. [Learn more](/api_guide/tags_update.html)"
      operationId: putTag
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: PUT (Update) a Tag
      tags:
      - Contact Tags
      x-authorization-privileges:
      - contacts:write
  /contact_tags:
    get:
      description: |-
        Use this endpoint to get details for all tags in your account. Use the <code>include_count</code> query parameter to include the total number of contacts assigned each tag. Use the <code>limit</code> query parameter to limit the number of tag results returned per page. To get the next page of results, copy the <code>cursor={the cursor ID}</code> from the resulting href link and add it (<code>&</code>) to the URL. For example:

        <p><code>/v3/contact_tags?limit=1&cursor=</code></p><p><code>bGltaXQ9MSZuZXh0PTJjZDgwMjdhLTc4YzAtMTFlOS1iZmQwLWZhMTYzZTZiMDFjMQ=</code></p>
        To learn more, see [Get Tags](/api_guide/tags_get.html).
      operationId: getAllTags
      security:
      - oauth2_implicit:
        - contact_data
        oauth2_access_code:
        - contact_data
      summary: GET Details for All Tags
      tags:
      - Contact Tags
      x-authorization-privileges:
      - contacts:read
      x-sdk-methodName: getAllTags
    post:
      description: "Use this method to create a new tag. The tag `name` is required\
        \ and must be unique and can include most common keyboard symbols. Optionally,\
        \ when creating a new tag you can specify the source (`tag_source`) used to\
        \ identify the contacts to tag in the request body. [Learn more](/api_guide/tags_create.html)."
      operationId: postTag
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: POST (Create) a Tag
      tags:
      - Contact Tags
      x-authorization-privileges:
      - contacts:write
  /emails:
    get:
      description: |
        Use this method to list and get details about your email campaigns. By default, this method returns all email campaigns for the user account including deleted email campaigns. To get email campaigns within a date-range, use the `after_date` and `before_date` query parameters.

        This endpoint does not return campaign activity details for each email campaign in the collection. To get email campaign activity details for a single email campaign, use the GET `/emails/{campaign_id}` endpoint."
        <div class="Msg"><p class="note-text">This method does not currently support filtering results using the email campaign creation date.</p></div>
      operationId: getAllEmailCampaigns
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Collection of Email Campaigns
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getAllEmailCampaigns
    post:
      description: |
        Use this method to create a new email campaign. This method also creates new `primary_email` and `permalink` email campaign activities and associates them with the new email campaign.

        The request body must contain the `name` property and the `email_campaign_activities` array. The `name` must be unique. The `email_campaign_activities` array contains the main content of your email campaign and must include `format_type`, `from_name`, `from_email`, `reply_to_email`, `subject`, and `html_content` properties. The `from_email` address you use must use a verified email address for your account.
        NOTE: If you create an email campaign using a legacy (V7) format, Constant Contact automatically converts it to the newer custom code format.
      operationId: createEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: POST (Create) a New Email Campaign
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:write
      x-sdk-methodName: createEmailCampaign
  /emails/{campaign_id}:
    delete:
      description: |
        Use this method to delete an email campaign and the email campaign activities associated with the email campaign. You cannot delete an email campaign when it has a `Scheduled` status.

        Constant Contact users can restore deleted email campaigns using the UI.
      operationId: deleteEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: DELETE an Email Campaign
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:delete
      x-sdk-methodName: deleteEmailCampaign
    get:
      description: "Use this method to get details about a single email campaign and\
        \ campaign related activities. Details include the email campaign name, current\
        \ status, create date, last update date, and a list of campaign activities;\
        \ including the `campaign_activity_id` and `role`."
      operationId: getEmailCampaignById
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET Details About a Single Email Campaign
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getEmailCampaignById
    patch:
      description: Use this method to rename an email campaign. The name is not visible
        to contacts. The name must be unique and cannot exceed 80 characters. You
        cannot rename email campaigns that have a `Removed` status.
      operationId: patchEmailCampaignName
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: PATCH (Update) an Email Campaign Name
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:write
      x-sdk-methodName: patchEmailCampaignName
  /emails/campaign_id_xrefs:
    get:
      description: |
        <div class="Msg Msg--warning"><p class="note-text">Use this endpoint to migrate your locally stored V2 email campaign data to the new V3 format. Developers are expected to use this endpoint sparingly. This endpoint is NOT intended for regular or repeated use. Constant Contact will eventually deprecate and remove this endpoint.</p></div>

        Use this method to migrate your local V2 API email data to the V3 API format. For each value that you provide in the `v2_email_campaign_ids` query parameter, this method returns the corresponding V3 `campaign_id` and V3 `campaign_activity_id` UUID value. For more information on the changes to the email campaign resource model, see [V3 Email Campaign Resource Changes](/api_guide/v3_v2_email_campaign_deltas.html) in the API guide.
      operationId: getEmailCampaignXrefs
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Collection of V2 and V3 API Email Campaign Identifiers
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getEmailCampaignXrefs
  /emails/activities/{campaign_activity_id}:
    get:
      description: |
        Use this method to return a specific email campaign activity. Each email campaign activity contains the email content, metadata, and styling information of an email. Email campaign activities can also contain either contact lists or segments. Constant Contact uses this information to determine who to send the email campaign activity to when you schedule it. You cannot get email campaign activities that have a `REMOVED` status.
      operationId: getEmailCampaignActivity
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Single Email Campaign Activity
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getEmailCampaignActivity
    put:
      description: |
        Use this method to update an email campaign activity by including the complete email campaign activity with your changes in the request body. The request body requires the `from_name`, `from_email`, `reply_to_email`, and `subject` properties.

        You can only update email campaign activities that have the `primary_email` role and that are in `DRAFT` or `Done` status.
        When you use a PUT method to update a resource, the V3 API overwrites any properties that are missing in the request body. However, the V3 API does not overwrite subresources that you omit in the request body or missing properties in subresources. This method considers `physical_address_in_footer`, `document_properties`, `html_content`, and `permalink_url` subresources of the email campaign activity.
      operationId: updateEmailCampaignActivity
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: PUT (Update) An Email Campaign Activity
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:write
      x-sdk-methodName: updateEmailCampaignActivity
  /emails/activities/{campaign_activity_id}/schedules:
    delete:
      description: Use this method to unschedule an email campaign activity by deleting
        the schedule. You can only unschedule email campaign activities that are in
        `SCHEDULED` status. Unscheduling reverts the email campaign activity to the
        status prior to `SCHEDULED`.
      operationId: unscheduleEmailCampaignActivity
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: DELETE an Email Campaign Activity Schedule
      tags:
      - Email Scheduling
      x-authorization-privileges:
      - campaign:send
      x-sdk-methodName: unscheduleEmailCampaignActivity
    get:
      description: "Use this method to return the current schedule for an email campaign\
        \ activity. This schedule contains the date that Constant Contact will send\
        \ the email campaign activity to contacts. If the email campaign activity\
        \ is not in `SCHEDULED` status, this method returns an empty array and a 200\
        \ response code."
      operationId: getEmailCampaignActivitySchedule
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Campaign Activity Schedule
      tags:
      - Email Scheduling
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getEmailCampaignActivitySchedule
    post:
      description: "Use this method to schedule when Constant Contact will send an\
        \ email campaign activity to contacts. Use the `scheduled_date` request body\
        \ property to enter the ISO-8601 format date that you want Constant Contact\
        \ to send the email campaign activity on. \n\nBefore you schedule an email\
        \ campaign activity, you must update the email campaign activity and specify\
        \ which contacts you want Constant Contact to send the email to. When you\
        \ make a PUT call to update an email campaign activity, use the `contact_list_ids`\
        \ or `segment_ids` array to add contacts.\n\nYou can only schedule email campaign\
        \ activities that have the `primary_email` role and are in `DRAFT`, `DONE`,\
        \ or `ERROR` status. When you schedule an email campaign activity in `DONE`\
        \ status, Constant Contact does not send the email campaign activity to contacts\
        \ that already received it. Constant Contact only sends the email campaign\
        \ activity to any new contacts in the contact lists or segment you use.\n"
      operationId: scheduleEmailCampaignActivity
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: POST (Create) an Email Campaign Activity Schedule
      tags:
      - Email Scheduling
      x-authorization-privileges:
      - campaign:send
      x-sdk-methodName: scheduleEmailCampaignActivity
  /emails/activities/{campaign_activity_id}/tests:
    post:
      description: |
        Use this method to send a test email to specific email addresses. Test emails allow you to verify how the email campaign activity will look before you send it to contacts. This method uses the `email_addresses` array in the request body to determine the recipients of the test email. The test email does not process any dynamic content in the email campaign activity. Dynamic content includes contact and custom field variables.

        You can send up to 50 test emails each day. Each recipient you add to the `email_addresses` array in the request body counts towards this limit. Successfully sending a test email returns a 204 response code without a response body.
      operationId: testSendEmailCampaignActivity
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: POST Test Send an Email Campaign Activity
      tags:
      - Email Scheduling
      x-authorization-privileges:
      - campaign:send
      x-sdk-methodName: testSendEmailCampaignActivity
  /emails/activities/{campaign_activity_id}/previews:
    get:
      description: |
        Use this method to get the HTML preview of an email campaign activity. The HTML preview allows you to verify how the email campaign activity will look before you send it to contacts.

        Custom code emails (`format_type` 5) use the Constant Contact account owner's contact information to process contact, custom field, and account variables in the preview.

        This method returns the HTML preview encoded as a JSON string. You will need to decode the string before you can use it as valid HTML.
      operationId: getEmailCampaignActivityPreview
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET the HTML Preview of an Email Campaign Activity
      tags:
      - Email Scheduling
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getEmailCampaignActivityPreview
  /emails/activities/{campaign_activity_id}/send_history:
    get:
      description: "Use this method to return the send history of an email campaign\
        \ activity. This method returns the send history as an array containing an\
        \ object for each time you sent a specific email campaign activity to contacts.\
        \ \n\nEach send history object contains the email campaign activity send date,\
        \ the number of contacts it was sent to, and the contact lists or segments\
        \ used to send it. Each send history object also includes if the send attempt\
        \ completed or encountered an error, and the reason why each error occurred.\
        \ This method returns results in ascending order starting with the first send\
        \ attempt. \n\nIf the email campaign activity has not been sent to contacts,\
        \ this method returns a 200 response and an empty array.\n"
      operationId: getEmailCampaignActivitySendHistory
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET the Send History of an Email Campaign Activity
      tags:
      - Email Scheduling
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getEmailCampaignActivitySendHistory
  /emails/activities/{campaign_activity_id}/non_opener_resends:
    get:
      description: "Get details about a resend to non-openers campaign activity. If\
        \ resend activity does not exist for the specified `campaign_activity_id`,\
        \ an empty list is returned in the results. You can only create one resend\
        \ activity per email campaign."
      operationId: getResendEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET Details for a Resend to Non-openers Campaign Activity
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getResendEmailCampaign
    post:
      description: "Use this POST method to resend a primary campaign activity to\
        \ contacts that did not open a campaign activity that has a current `status`\
        \ of `Draft`, `Scheduled`, or `Done`. You can only create one resend activity\
        \ per email campaign.\n \n After an email campaign activity is sent to contacts,\
        \ Constant Contact waits the specified number of `delay_days` or `delay_minutes`\
        \ (properties are mutually exclusive) before resending to non-openers. If\
        \ you set both `delay_days` or `delay_minutes`, `delay_minutes` is ignored\
        \ in the request. You can resend to non-openers a minimum of twelve hours\
        \ (720 minutes) and a maximum of up to 10 days (or 10 x 1440 minutes) after\
        \ the initial send date.\n \n "
      operationId: createResendEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: POST a Resend to Non-openers Campaign Activity
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:send
      x-sdk-methodName: createResendEmailCampaign
  /emails/activities/{campaign_activity_id}/non_opener_resends/{resend_request_id}:
    delete:
      description: Use this `DELETE` method to delete (unschedule) a resend to non
        openers activity.
      operationId: deleteResendEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: DELETE a Resend to Non Openers Activity
      tags:
      - Email Campaigns
      x-authorization-privileges:
      - campaign:send
      x-sdk-methodName: deleteResendEmailCampaign
  /emails/activities/{campaign_activity_id}/abtest:
    delete:
      description: "Deletes an A/B Test on an primary email campaign activity. You\
        \ can only delete A/B tests that have a `current_status` of `Draft`. Deleting\
        \ an A/B tests reverts the email campaign activity `type` from A/B Test (code=\
        \ `57`) back to NewsLetter (code= `10`). Constant Contact uses the original\
        \ subject line, rather than the alternate A/B test subject line, when an A/B\
        \ test is deleted."
      operationId: deleteABTestEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: DELETE an A/B Test for an Email Campaign Activity
      tags:
      - Email Campaigns AB Tests
      x-authorization-privileges:
      - campaign:write
      x-sdk-methodName: deleteABTestEmailCampaign
    get:
      description: "Use this method to get A/B test details for a primary email campaign\
        \ activity, such as the alternate email subject line, the contact test percentage\
        \ size, and the number of hours to wait to determine the winning subject line\
        \ to use. Currently, A/B tests support subject line only."
      operationId: getABTestEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET A/B Test Details for an Email Campaign Activity
      tags:
      - Email Campaigns AB Tests
      x-authorization-privileges:
      - campaign:read
      x-sdk-methodName: getABTestEmailCampaign
    post:
      description: "Use this method to create a new A/B test for a primary email campaign\
        \ activity. You must specify an alternative subject line, the percentage of\
        \ contact to use for the A/B test, and the number of hours to wait after the\
        \ A/B test is sent before determining the winning subject line. To create\
        \ an A/B test, the campaign must have a `current_status` of `DRAFT`. When\
        \ you create an A/B test, the `type` changes from Newsletter (code= `10`)\
        \ to A/B Test (code= `57`)."
      operationId: createABTestEmailCampaign
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: POST (Create) an A/B Test for an Email Campaign Activity
      tags:
      - Email Campaigns AB Tests
      x-authorization-privileges:
      - campaign:write
      x-sdk-methodName: createABTestEmailCampaign
  /reports/contact_reports/{contact_id}/activity_details:
    get:
      description: |-
        <p>Gets the tracking activity data for a single contact, sorted in descending activity date order.</p> <p>You must chose either the `tracking_activities_list` query parameter and or the `tracking_activity_type` query parameter to specify one or more tracking activity types In the request. The `tracking_activities_list`  and `tracking_activities_type` query parameters are mutually exclusive.</p>
              <table><tr><td colspan='2'>Valid tracking activity types</td></tr>
                <tr><td><b>em_sends</b></td><td>Send activities</td></tr>
                <tr><td><b>em_opens</b></td><td>Email open tracking activities</td></tr>
                <tr><td><b>em_clicks</b></td><td>Link click-through tracking activities</td></tr>
                <tr><td><b>em_bounces</b></td><td>Bounce tracking activities</td></tr>
                <tr><td><b>em_optouts</b></td><td>Opt-out tracking activities</td></tr><tr>
                <td><b>em_forwards</b></td><td>Forward to a friend tracking activities</td></tr>
                <tr><td><b>p_contact_open</b></td><td>Landing page opens</td></tr>
                <tr><td><b>p_contact_click</b></td><td>Landing page clicks</td></tr>
                <tr><td><b>p_contact_add</b></td><td>Landing page adds</td></tr>
                <tr><td><b>p_contact_update </b></td><td> Landing page updates</td></tr>
              </table>
      operationId: getContactTrackingReport
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Contact Activity Details
      tags:
      - Contacts Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getContactTrackingReport
  /reports/contact_reports/{contact_id}/open_and_click_rates:
    get:
      description: "<p>Gets the average open and click rate for a given account and\
        \ contact.<p>Looks at all tracking activities for bulk emails from a given\
        \ contact over the given date range. Range cannot exceed 5 years.</p><p>Returns\
        \ the rates and the number of campaign activities that were included in the\
        \ calculation.</p><p>If no activities fall into the given date range, all\
        \ rates will return 0 and the number of included activities will be 0.</p>"
      operationId: getContactOpenClickRateReport
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Average Open and Click Rates
      tags:
      - Contacts Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getContactOpenClickRateReport
  /reports/contact_reports/{contact_id}/activity_summary:
    get:
      description: "Get a list of the recent emails (aka, campaign activities) sent\
        \ to a specific contact and a summary of the actions the contact took on that\
        \ email for the most recent 200 campaigns."
      operationId: getContactTrackingCountReport
      security:
      - oauth2_implicit:
        - contact_data
      - oauth2_access_code:
        - contact_data
      summary: GET Contact Action Summary
      tags:
      - Contacts Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getContactTrackingCountReport
  /reports/email_reports/{campaign_activity_id}/links:
    get:
      description: |-
        Use this method to return link details, including the number of unique contacts that clicked each link in an email campaign activity, and the type of action associated with clicking each link. To include link details for links that were not clicked, set the `no_clicks` query parameter to `true`.

        You can return reporting data for `primary_email` and `resend` role email campaign activities. For more use case information, see [Get an Email Links Report](/api_guide/email_links_report.html) in the API guide.
      operationId: getCampaignActivityLinkReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Links Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getCampaignActivityLinkReport
  /reports/email_reports/{campaign_activity_id}/tracking/sends:
    get:
      description: "Use this method to get each contact that was sent a specific email\
        \ campaign activity. This sends report includes general contact data such\
        \ as the date and time that the email campaign activity was sent to a contact's\
        \ email address, the contact's first and last name, and unique ID. This report\
        \ lists the most recent activity first. For more use case information, see\
        \ [Get an Sends report for an Email Campaign Activity](/api_guide/email_summary_sends_report.html)\
        \ in the API guide."
      operationId: getEmailSendsReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Sends Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getEmailSendsReport
  /reports/email_reports/{campaign_activity_id}/tracking/opens:
    get:
      description: "Use this method to get each time a contact opened a specific email\
        \ campaign activity. This report includes general contact information such\
        \ as the contact's email address and unique ID, the date and time they opened\
        \ the email campaign activity, and the type of device they used to open it.\
        \ This report lists the most recent activity first. For more use case information,\
        \ see [Get an Opens report for an Email Campaign Activity](/api_guide/email_summary_opens_report.html)\
        \ in the API guide."
      operationId: getEmailOpensReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Opens Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getEmailOpensReport
  /reports/email_reports/{campaign_activity_id}/tracking/unique_opens:
    get:
      description: "Use this method to get a unique opens report that provides details\
        \ about the last time that each contact opened the specified email campaign\
        \ activity. This report includes general contact information such as the contact's\
        \ email address and unique ID, the date and time they opened the email campaign\
        \ activity, and the type of device they used to open it. This report lists\
        \ the most recent activity first. For more use case information, see [Get\
        \ an Unique Opens Report for an Email Campaign Activity](/api_guide/email_summary_unique_opens_report.html)\
        \ in the API guide."
      operationId: getUniqueOpensReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Unique Opens Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getUniqueOpensReport
  /reports/email_reports/{campaign_activity_id}/tracking/didnotopens:
    get:
      description: "Use this method to get a report listing each contact that was\
        \ sent, but did not open the specified email campaign activity. This report\
        \ lists contact information such as the contact's email address and unique\
        \ ID, and the date and time that the email campaign activity was sent. This\
        \ report lists the most recent activity first. For more use case information,\
        \ see [Get a Did Not Opens Report for an Email Campaign Activity](/api_guide/email_summary_non_opens_report.html)\
        \ in the API guide."
      operationId: getDidNotOpensReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Did Not Opens Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getDidNotOpensReport
  /reports/email_reports/{campaign_activity_id}/tracking/clicks:
    get:
      description: "Use this method to get each time a contact clicked a link, the\
        \ click date and time, and the device type they used. Use the `url_id` query\
        \ parameter to get a clicks report for a specific link URL. Clicks report\
        \ data is sorted with most recent activity listed first."
      operationId: getClicksReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Clicks Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getClicksReport
  /reports/email_reports/{campaign_activity_id}/tracking/forwards:
    get:
      description: "Use this method to get a report listing each time a contact forwarded\
        \ the email campaign activity using the forwarding link in the email footer.\
        \ The report includes general contact information, such as the contact's email\
        \ address and unique ID, and the date and time that the email campaign activity\
        \ was forwarded. Forwards report data is sorted with the most recent activity\
        \ listed first. For more use case information, see [Get an Email Forwards\
        \ Report](/api_guide/email_summary_forwards_report.html) in the API guide."
      operationId: getForwardsReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Forwards Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getForwardsReport
  /reports/email_reports/{campaign_activity_id}/tracking/optouts:
    get:
      description: "Use this method to get a report listing each contact that clicked\
        \ the unsubscribe link in the email campaign activity to opt-out from receiving\
        \ emails sent from your Constant Contact account. This report includes contact\
        \ information, such as the contact's email address, unique ID, and the opt-out\
        \ date and time. Opt-out report data is sorted with the most recent activity\
        \ listed first. For more use case information, see [Get an Email Opt-outs\
        \ Report](/api_guide/email_summary_optouts_report.html) in the API guide."
      operationId: getOptoutsReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Opt-outs Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getOptoutsReport
  /reports/email_reports/{campaign_activity_id}/tracking/bounces:
    get:
      description: |-
        Use this method to get a report listing contact bounce data for the specified email campaign activity. This report lists the most recent bounce data first and includes contact information, such as the contact's email address, unique ID, and the email bounce date and time.
        Use the <code>bounce_code</code> query parameter to limit the type of bounce data to return.

        For more use case information, see [Get a Bounces Report for an Email Campaign Activity](/api_guide/email_summary_bounces_report.html) in the API guide.
      operationId: getBouncesReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Bounces Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getBouncesReport
  /reports/summary_reports/email_campaign_summaries:
    get:
      description: |-
        Use this method to get aggregate email campaign statistics for up to five hundred email campaigns. The response results include the total number of times that each contact uniquely interacted with each tracked campaign activity.

        Results are sorted in descending order by the date that the email was last sent (<code>last_sent_date</code>). Use the <code>limit</code> query parameter to limit the number of email campaign summary reports listed on each page.



         For more use case information, see "[Get an Email Campaign Summary Report](/api_guide/email_bulk_campaign_summary_report.html)"
      operationId: getEmailCampaignReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Campaigns Summary Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getEmailCampaignReport
  /reports/stats/email_campaigns/{campaign_ids}:
    get:
      description: |-
        Use this method to get email campaign performance tracking statistics for one or more campaigns, including the total number of times contacts interacted with your campaigns and how.

        For each `campaign_id`, this method returns lists that include total counts (`stats`) for each type of tracked email and relevant campaign-related percentages (`percents`). It also returns the date and time at which the campaign stats were last refreshed.
        If any specified `campaign_id` is invalid, a 404 error response is returned for all campaigns.
      operationId: getEmailStatsReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Campaign Stats Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getEmailStatsReport
  /reports/stats/email_campaign_activities/{campaign_activity_ids}:
    get:
      description: |-
        Use this method to get performance tracking statistics for up to ten email campaign activities. Statistics include the total number of times contacts interacted with your campaigns and how.

        For each `campaign_activity_id`, this method returns the `campaign_id`, the total counts (`stats`) for each type of tracked email activity, and the date and time that Constant Contact last refreshed (`last_refresh_time`) the `stats`.

        When requesting statistics for multiple email campaign activities, if one or more of the `campaign_activity_ids` do not exist, were deleted, or do not have any stats associated with it, the `campaign_activity_ids` and error details display under `errors`. If any single specified `campaign_activity_id` is invalid (malformed), a 404 error response is returned for all campaign activities.
      operationId: getEmailCampaignActivityReport
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an Email Campaign Activity Stats Report
      tags:
      - Email Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
      x-sdk-methodName: getEmailCampaignActivityReport
  /reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_clicks:
    get:
      description: "Use this method get details about each contact that clicked a\
        \ link on a landing page campaign activity. Unique contact clicks are identified\
        \ by both the `contact_id` and `url_id`. The same contact may appear more\
        \ than once in the results, if they clicked more than one link on the landing\
        \ page. The resulting contact data is listed with most recent activity first."
      operationId: getUniqueContactClicks
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Unique Contacts Clicks Landing Page Report
      tags:
      - Landing Pages Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
  /reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_opens:
    get:
      description: Use this method get details about each contact that opens a link
        on a landing page. Contacts are uniquely identified by `contact_id`.  The
        resulting contact data is listed with most recent activity first.
      operationId: getUniqueContactOpens
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Unique Contacts Opens Landing Page Report
      tags:
      - Landing Pages Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
  /reports/landing_pages/campaign_details/{campaign_activity_id}/p_contact_opens:
    get:
      description: Use this method get contact details for each time a contact opens
        a link on a landing page.  The resulting contact data is listed with most
        recent activity first.
      operationId: getContactOpens
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Contacts Opens Landing Page Report
      tags:
      - Landing Pages Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
  /reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_updates:
    get:
      description: Use this method to get contact details for each contact that updated
        their contact data from a landing page. Contacts are uniquely identified by
        `contact_id`.  The resulting contact data is listed with most recent activity
        first.
      operationId: getUniqueContactUpdates
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Unique Contacts Updates Landing Page Report
      tags:
      - Landing Pages Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
  /reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_adds:
    get:
      description: Use this method to get details about each contact added to the
        account from a specified landing page. Contacts are identified by `contact_id`.
        The resulting contact data is listed with most recent activity first.
      operationId: getContactAdds
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Unique Contacts Adds Landing Page Report
      tags:
      - Landing Pages Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
  /reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_sms_optins:
    get:
      description: Use this method get details about unique contacts that click a
        link on a landing page to opt in to receiving SMS text messages. Contacts
        are uniquely identified by `contact_id``.  The resulting contact data is listed
        with most recent activity first.
      operationId: getUniqueContactSMSOptIns
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET a Unique Contacts SMS Opt-In Landing Page Report
      tags:
      - Landing Pages Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
  /reports/summary_reports/sms_campaign_summaries:
    get:
      description: "Use this method to get SMS campaign summary details, including\
        \ the total number of times that each contact uniquely interacted with each\
        \ tracked campaign activity and aggregate tracking statistics. Results are\
        \ sorted in descending order by the date the SMS was last sent (`last_sent_date`).\n\
        The `start_at` date is required. Use both the `start_at` and `end_at` date\
        \ query parameters to return only SMS campaign summary details that occurred\
        \ within a specified date range.\nUse the `limit` query parameter to limit\
        \ the number of results returned per page. "
      operationId: getAllBulkSmsCampaignSummaries
      security:
      - oauth2_implicit:
        - campaign_data
      - oauth2_access_code:
        - campaign_data
      summary: GET an SMS Campaigns Summary Report
      tags:
      - SMS Reporting
      x-authorization-privileges:
      - ui:campaign:metrics
components:
  securitySchemes:
    oauth2_implicit:
      flows:
        implicit:
          authorizationUrl: https://authz.constantcontact.com/oauth2/default/v1/token
          scopes:
            contact_data: Read or modify contact data.
            campaign_data: Read or modify email campaign data.
            account_read: Read account data.
            account_update: Modify account data.
      type: oauth2
    oauth2_access_code:
      flows:
        authorizationCode:
          authorizationUrl: https://authz.constantcontact.com/oauth2/default/v1/authorize
          scopes:
            contact_data: Read or modify contact data.
            campaign_data: Read or modify email campaign data.
            account_read: Read account data.
            account_update: Modify account data.
          tokenUrl: https://authz.constantcontact.com/oauth2/default/v1/token
      type: oauth2

